### ISSUE TITLE
安装报错，然后就停止了

### ISSUE THREAD

**Issue by tension** [midoks/mdserver-web#10]
```sh
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-21.3.1 setuptools-59.6.0 wheel-0.37.1
sh: line 103: cd: /www/server/mdserver-web/scripts: No such file or directory
chmod: cannot access '/www/server/mdserver-web/data': No such file or directory
sh: line 110: cd: /www/server/mdserver-web: No such file or directory
sh: line 112: cd: /www/server/mdserver-web: No such file or directory
sh: line 115: cd: /www/server/mdserver-web: No such file or directory
sh: line 116: cd: /www/server/mdserver-web: No such file or directory
sh: line 117: cd: /www/server/mdserver-web: No such file or directory
Time consumed: 9 Minute!
```

**Comment by weiyidu** [comment]
我正常安装完成，但安装插件不怎么搞

**Comment by tension** [comment]
> 

你是什么系统安装的，我用的 RockyLinux 8.5

**Comment by weiyidu** [comment]
> > 
> 
> 你是什么系统安装的，我用的 RockyLinux 8.5

CentOS 7
5.18.2-1.el7.elrepo.x86_64

**Comment by tension** [comment]
> > > 
> > 
> > 
> > 你是什么系统安装的，我用的 RockyLinux 8.5
> 
> CentOS 7 5.18.2-1.el7.elrepo.x86_64

知道了，我试试 CentOS

**Comment by midoks** [comment]
我都用centos测试的，其他系统，没有其他测试机。

**Comment by midoks** [comment]
> > 我都用centos测试的，其他系统，没有其他测试机。
> 
> 环境：CentOS 7 5.18.2-1.el7.elrepo.x86_64
> 
> PHP 安装不上，HOSTLOC的朋友应该乐意提供给你测试机。

提供一下报错的信息。

**Comment by weiyidu** [comment]
> > > 我都用centos测试的，其他系统，没有其他测试机。
> > 
> > 
> > 环境：CentOS 7 5.18.2-1.el7.elrepo.x86_64
> > PHP 安装不上，HOSTLOC的朋友应该乐意提供给你测试机。
> 
> 提供一下报错的信息。

没有使用提示，在面板安装完成后，还提示安装。

**Comment by midoks** [comment]
> 提示安装

面板安装->所需软件安装[手动](openresty,php,mysql)-> 创建web

**Comment by dreampen123** [comment]
好像再安装一次就行了，但是国内测试，php啥的软件都无法安装，更新提示网络问题。有啥办法么？是不是环境包被屏蔽了

**Comment by midoks** [comment]
基本完成ubuntu,debian,fedora的面板安装问题，基础插件测试完成后会释出新版本。非主要插件，需要更长时间检验。
