### ISSUE TITLE
OP防火墙开启时通过MySQL管理界面打开phpmyadmin时500错误

### ISSUE THREAD

**Issue by yfzuix** [midoks/mdserver-web#102]
## 什么系统 ?

debian10

## 错误信息 ?

phpmyadmin错误日志

```
2022/06/25 17:34:22 [error] 21881#0: *1 lua entry thread aborted: runtime error: /www/server/openresty/nginx/conf/waf/lua/init.lua:320: attempt to index global 'request_header' (a nil value)
stack traceback:
coroutine 0:
	/www/server/openresty/nginx/conf/waf/lua/init.lua: in function 'post_data_chekc'
	/www/server/openresty/nginx/conf/waf/lua/init.lua:563: in function 'waf'
	/www/server/openresty/nginx/conf/waf/lua/init.lua:578: in main chunk, client: 171.***.***.***, server: 127.0.0.1, request: "POST /phpmyadmin/index.php HTTP/1.1", host: "121.***.***.***:888", referrer: "http://121.***.***.***:58888/soft"
```
## 问题描述

开发版 (MySQL5.7 PHP7.4 phpmyadmin5.2)   chrome和Firefox浏览器结果一样

开启OP防火墙，点击MySQL--管理列表--phpMyAdmin按钮，phpmyadmin就无法打开，提示500 Internal Server Error，但是点击phpmyadmin5.2管理界面--主页按钮就能打开；关闭OP防火墙后两种方式正常打开。

防火墙是否开启，直接链接访问都正常。

**Comment by tudou88** [comment]
我的也是这种情况，目前添加好网站，显示404 Not Found - openresty  技术小白，折腾半天没搞定

**Comment by midoks** [comment]
经检查，是waf的问题，已经修复。更新后，一定要先停止再启动，就会正常。

**Comment by xiaomoy** [comment]
> 经检查，是waf的问题，已经修复。更新后，一定要先停止再启动，就会正常。

复现
2022/10/23 10:03:31 [error] 511#0: *79 lua entry thread aborted: runtime error: /www/server/op_waf/waf/lua/init.lua:298: attempt to index a nil value
stack traceback:
coroutine 0:
	/www/server/op_waf/waf/lua/init.lua: in function 'is_open_waf_cc_increase'
	/www/server/op_waf/waf/lua/init.lua:316: in function 'waf_cc_increase'
	/www/server/op_waf/waf/lua/init.lua:531: in function 'waf'
	/www/server/op_waf/waf/lua/init.lua:553: in main chunk, client: 0.0.0.0

**Comment by midoks** [comment]
mw update_dev  
重载 即可
