### ISSUE TITLE
面板搭建纯静态网站，目录和面板设置目录不符

### ISSUE THREAD

**Issue by LoserFox** [midoks/mdserver-web#108]
## 什么系统 ?

Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-105-generic s390x)

## 错误信息 ?

面板静态网站文件存放地址有误，并不是设置的目录。而是nginx默认的/var/www/

## 浏览器版本 ?

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0

## 软件版本(插件/面板) ?

0.8.6.1

另外作者有能力建一个Telegram交流群吗，这样就不必每个人都跑来issue撒欢了

**Comment by midoks** [comment]
这个bug是解决了，但是要手动删除 
/www/server/openresty/init.d手动重新启动。才能生效。

更新到最新版本。

**Comment by LoserFox** [comment]
> 这个bug是解决了，但是要手动删除 /www/server/openresty/init.d手动重新启动。才能生效。
> 
> 更新到最新版本。

问题解决，有时间建个交流群什么的吗

**Comment by midoks** [comment]
吹水组 - https://t.me/mdserver_web
