### ISSUE TITLE
php GD库问题

### ISSUE THREAD

**Issue by siamoe** [midoks/mdserver-web#112]
## 什么系统 ?

Centos 7.9

## 错误信息 ?
安装的时候不支持JPEG,查看phpinfo里面GD库也是安装上的,不知道是什么问题，php5.6 7.2 8.1 都安装了一遍，也是该问题，其他版本的PHP没测试
Ex:
```bash
................start mw success
bash: line 149: ./scripts/init.d/mw: No such file or directory
```

## 错误截图 ?
![图片](https://user-images.githubusercontent.com/102142539/176177567-87007da6-130c-49d9-b35e-a8bf804776b2.png)

![图片](https://user-images.githubusercontent.com/102142539/176177457-c6310ff0-fcae-4c3f-9d71-c05ab12efa1f.png)

## 浏览器版本 ?

Google Chrome

## 软件版本(插件/面板) ?

php7.2

**Comment by midoks** [comment]
已经加入，需要重装。php52，没有。php74之后不能安装就能支持。需要在扩展里安装。
