### ISSUE TITLE
离线部署

### ISSUE THREAD

**Issue by yizhitangtongxue** [midoks/mdserver-web#124]
## 需求

内网环境，请问未来会支持离线部署吗

**Comment by soxft** [comment]
离线部署好像 不太方便 很多python的库或者一些运行环境 都需要从外部拉下来编译
全部打包在一起可能不太方便？

**Comment by yizhitangtongxue** [comment]
> 

那可能只有装好需要的环境再用docker打包了

**Comment by midoks** [comment]
你可以构建一个文件目录，在/www/server/source，把需要的文件一起打包。即可在内网部署。
