### ISSUE TITLE
管理页面无法绑定域名

### ISSUE THREAD

**Issue by nozomileng** [midoks/mdserver-web#134]
debian11
面板0.8.6.9
管理页面绑定域名无用，填写了域名确定显示成功但是刷新完还是空白。
![image](https://user-images.githubusercontent.com/51223245/179958735-49af3118-8c06-4cdd-a3cb-a04970002ec6.png)
该xxx.xxx.xxx为网站搭建使用的可正常使用域名。
![image](https://user-images.githubusercontent.com/51223245/179958874-e1c36488-b40f-4c07-acc1-8476fe9071e2.png)

**Comment by midoks** [comment]
面板的域名绑定无效-已经关闭。
