### ISSUE TITLE
能搞个Python项目管理器吗？

### ISSUE THREAD

**Issue by allcdn** [midoks/mdserver-web#136]
## 需求

想开发一个什么插件?
想有什么功能?
Python项目管理器和宝塔的差不多就行

## 提供参考

给开发者提供参考！

**Comment by midoks** [comment]
已有。

**Comment by LoveHeiZhu** [comment]
Python项目管理器，mds面板确实没有，希望有大佬移植一下，这样的话，跑python项目将非常方便
