### ISSUE TITLE
后台修改了别名，前端不显示

### ISSUE THREAD

**Issue by malou8** [midoks/mdserver-web#141]
## 什么系统 ?

Debian11

## 错误信息 ?

在后台设置里面修改了别名，退出后登录口不显示别名信息，依旧显示“mdserver-web”

## 错误截图 ?

...

## 浏览器版本 ?

谷歌86

## 软件版本(插件/面板) ?

0.8.6.11

**Comment by midoks** [comment]
已经优化。
