### ISSUE TITLE
MariaDB 一直安装不上

### ISSUE THREAD

**Issue by 5la** [midoks/mdserver-web#142]
## 什么系统 ?

Debian 11

## 错误信息 ?

Ex:
```bash
................start mw success
bash: line 149: ./scripts/init.d/mw: No such file or directory
```

## 错误截图 ?
![1659065665873](https://user-images.githubusercontent.com/86772550/181677488-177c471e-b1c5-4091-b79c-04d0f737ee05.jpg)

...

## 浏览器版本 ?
chrome 101
...

## 软件版本(插件/面板) ?
MariaDB 10.6 10.7 10.8
...

**Comment by midoks** [comment]
没有安装过程日志。

**Comment by midoks** [comment]
没有安装过程日志。

**Comment by 5la** [comment]
+ PATH='/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin'
+ export PATH
++ pwd
+ curPath=/www/server/mdserver-web/plugins/mariadb
++ dirname /www/server/mdserver-web/plugins/mariadb
+ rootPath=/www/server/mdserver-web/plugins
++ dirname /www/server/mdserver-web/plugins
+ rootPath=/www/server/mdserver-web
++ dirname /www/server/mdserver-web
+ serverPath=/www/server
++ uname
+ sysName=Linux
+ install_tmp=/www/server/mdserver-web/tmp/mw_install.pl
+ mariadbDir=/www/server/source/mariadb
+ MY_VER=10.6.8
+ action=install
+ '[' install == install ']'
+ Install_app
+ mkdir -p /www/server/source/mariadb
+ echo 正在安装脚本文件...
+ id mysql
+ groupadd mysql
+ useradd -g mysql mysql
+ '[' Linux '!=' Darwin ']'
+ mkdir -p /var/log/mariadb
+ touch /var/log/mariadb/mariadb.log
+ '[' '!' -f /www/server/source/mariadb/mariadb-10.6.8.tar.gz ']'
+ wget -O /www/server/source/mariadb/mariadb-10.6.8.tar.gz --tries=3 https://downloads.mariadb.org/interstitial/mariadb-10.6.8/source/mariadb-10.6.8.tar.gz
--2022-07-31 09:45:47--  https://downloads.mariadb.org/interstitial/mariadb-10.6.8/source/mariadb-10.6.8.tar.gz
Resolving downloads.mariadb.org (downloads.mariadb.org)... 116.203.207.31, 2a01:4f8:c2c:b04e::1
Connecting to downloads.mariadb.org (downloads.mariadb.org)|116.203.207.31|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /rest-api/mariadb/10.6.8/mariadb-10.6.8.tar.gz [following]
--2022-07-31 09:45:48--  https://downloads.mariadb.org/rest-api/mariadb/10.6.8/mariadb-10.6.8.tar.gz
Reusing existing connection to downloads.mariadb.org:443.
HTTP request sent, awaiting response... 302 Found
Location: https://mirrors.xtom.com.hk/mariadb//mariadb-10.6.8/source/mariadb-10.6.8.tar.gz [following]
--2022-07-31 09:45:48--  https://mirrors.xtom.com.hk/mariadb//mariadb-10.6.8/source/mariadb-10.6.8.tar.gz
Resolving mirrors.xtom.com.hk (mirrors.xtom.com.hk)... 45.125.0.6, 2403:2c80:5::6
Connecting to mirrors.xtom.com.hk (mirrors.xtom.com.hk)|45.125.0.6|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-07-31 09:45:49 ERROR 403: Forbidden.

+ '[' '!' -d /www/server/source/mariadb/mariadb-10.6.8 ']'
+ cd /www/server/source/mariadb
+ tar -zxvf /www/server/source/mariadb/mariadb-10.6.8.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
+ '[' '!' -d /www/server/mariadb ']'
+ cd /www/server/source/mariadb/mariadb-10.6.8
/www/server/mdserver-web/plugins/mariadb/versions/10.6/install.sh: line 47: cd: /www/server/source/mariadb/mariadb-10.6.8: No such file or directory
+ make
make: *** No targets specified and no makefile found.  Stop.
+ '[' -d /www/server/mariadb ']'
+ echo 安装失败
+ echo 'install fail'
install fail
+ exit 1
