### ISSUE TITLE
域名访问MW面板

### ISSUE THREAD

**Issue by nozomileng** [midoks/mdserver-web#147]
需求：
1、指定域名加端口访问MW面板，现在http域名加端口可以访问，但是https域名加端口就不能访问。不然就要无痕模式去掉s才能访问。
2、限制指定的ip才能访问MW面板。
3、默认关闭伪静态。

参考宝塔的面板设置功能

**Comment by midoks** [comment]
1.浏览器里有缓存。
2.暂时不加。
3.已关闭。
