### ISSUE TITLE
MW面板支持ARM机器了吗

### ISSUE THREAD

**Issue by malou8** [midoks/mdserver-web#155]
甲骨文ARM很想用[mdserver-web](https://github.com/midoks/mdserver-web)

**Comment by midoks** [comment]
未有人提供机器。无法测试，无法解决。

**Comment by midoks** [comment]
经过别人给我的测试机测试，综合别人给我信息和我自己的测试，是你自己的设置的问题。

![2022-08-13 01 05 59](https://user-images.githubusercontent.com/4169529/184409385-6a6c2247-897b-43e9-8b3e-984db641023e.jpg)
