### ISSUE TITLE
同时存在ufw和firewalld，会出现500错误

### ISSUE THREAD

**Issue by guiduan** [midoks/mdserver-web#16]
https://github.com/midoks/mdserver-web/blob/e40eea1a7c2280b2e456975397e5541470175665/class/core/firewall_api.py#L294

**Comment by guiduan** [comment]
> https://github.com/midoks/mdserver-web/blob/e40eea1a7c2280b2e456975397e5541470175665/class/core/firewall_api.py#L294

貌似是由于393行判断ufw进程号的问题
`cmd = "ps -ef|grep ufw |grep -v grep | awk '{print $2}'"`
在ubuntu 20.04中貌似不能用ps来获取ufw的进程号。

**Comment by midoks** [comment]
已经修复
