### ISSUE TITLE
防盗链无法通过勾选勾掉开启关闭

### ISSUE THREAD

**Issue by DaoChen6** [midoks/mdserver-web#162]
## 什么系统 ?

debian11

## 错误信息 ?

防盗链无法通过勾选勾掉开启关闭

## 错误截图 ?

![image](https://user-images.githubusercontent.com/63903027/184513517-cb81f0c3-a858-46a3-8345-565926b2c14f.png)
![1660428866008](https://user-images.githubusercontent.com/63903027/184513691-ad3bd3ab-55c1-47e2-860b-71ed49573ae0.png)

## 浏览器版本 ?

edge 104.0.1293.47

## 软件版本(插件/面板) ?

面板 0.9.4
OpenResty 1.21.4.1

**Comment by midoks** [comment]
ok,已经修复。 等几天更新。
