### ISSUE TITLE
MariaDB 10.8 备份导入功能不可用

### ISSUE THREAD

**Issue by WankkoRee** [midoks/mdserver-web#164]
## 什么系统 ?

Debian 11

## 浏览器版本 ?

Microsoft Edge 104.0.1293.54

## 软件版本(插件/面板) ?

`MW 0.9.4`
`mariadb-10.8`

----

## 错误信息 ?

```text
sh:行1: /www/server/mysql/bin/mysql: 没有那个文件或目录
```

## 错误截图 ?

![image](https://user-images.githubusercontent.com/21287731/184538541-b0910ff5-334c-469e-aa28-5514f65e41ff.png)

----

尝试将`mariadb`插件的`index.py:696`从`mysql_cmd = mw.getRootDir() + '/server/mysql/bin/mysql -uroot -p' + pwd + \`改为`mysql_cmd = getServerDir() + '/bin/mysql -uroot -p' + pwd + \`，上述问题解决，但是出现新的问题：

----

## 错误信息 ?

```text
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
```

## 错误截图 ?

![image](https://user-images.githubusercontent.com/21287731/184538719-058f1f5d-7a4b-4d95-80ff-606b69528af9.png)

----

推测是由于`mysql/mariadb`客户端默认使用了`/etc/mysql/my.cnf`造成的。此目录在全新安装完`MW`之后就会出现（此时还未安装`mariadb`），文件内容：

```
# The MariaDB configuration file
#
# The MariaDB/MySQL tools read configuration files in the following order:
# 0. "/etc/mysql/my.cnf" symlinks to this file, reason why all the rest is read.
# 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
# 2. "/etc/mysql/conf.d/*.cnf" to set global options.
# 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
# 4. "~/.my.cnf" to set user-specific options.
#
# If the same option is defined multiple times, the last one will apply.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# If you are new to MariaDB, check out https://mariadb.com/kb/en/basic-mariadb-articles/

#
# This group is read both by the client and the server
# use it for options that affect everything
#
[client-server]
# Port or socket location where to connect
# port = 3306
socket = /run/mysqld/mysqld.sock

# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/
```

**Comment by midoks** [comment]
这个问题已经修复了，在dev更新，没有问题了。。
是由于改为sock访问模式: mysql -S ../mysql.sock  -uroot -p 
还有这种方式: mysql --defaults-file==*/my.conf -uroot-p
