### ISSUE TITLE
debian11 JSDelivr    mariadb-10.8安装失败 DEV没问题

### ISSUE THREAD

**Issue by RoyalSwift** [midoks/mdserver-web#167]
**### DEV没问题**

**Comment by RoyalSwift** [comment]
不是DEV

**Comment by RoyalSwift** [comment]
+ cpuCore=4
++ free -m
++ grep Mem
++ awk '{printf("%.f",($2)/1024)}'
+ MEM_INFO=4
+ '[' 4 '!=' 1 ']'
+ '[' 4 '!=' 0 ']'
+ '[' 4 -gt 4 ']'
+ '[' 4 -gt 1 ']'
++ echo 4
++ awk '{printf("%.f",($1)*0.8)}'
+ cpuCore=3
+ cd /www/server/mdserver-web/plugins/mysql/lib
+ /bin/bash rpcgen.sh
/bin/rpcgen
+ INSTALL_CMD=cmake
++ cmake -version
++ grep version
++ awk '{print $3}'
++ awk -F . '{print $1}'
+ CMAKE_VERSION=3
+ '[' 3 -eq 2 ']'
+ '[' '!' -f /www/server/source/mysql/mysql-boost-8.0.28.tar.gz ']'
+ md5_mysql_ok=362b8141ecaf425b803fe55292e2df98
+ '[' -f /www/server/source/mysql/mysql-boost-8.0.28.tar.gz ']'
++ awk '{print $1}'
++ md5sum /www/server/source/mysql/mysql-boost-8.0.28.tar.gz
+ md5_mysql=362b8141ecaf425b803fe55292e2df98
+ '[' 362b8141ecaf425b803fe55292e2df98 == 362b8141ecaf425b803fe55292e2df98 ']'
+ echo 'mysql8.0 file  check ok'
mysql8.0 file  check ok
+ '[' '!' -d /www/server/source/mysql/mysql-8.0.28 ']'
+ OPTIONS=
++ openssl version
++ awk '{print $2}'
++ awk -F . '{print $1}'
+ OPENSSL_VERSION=1
+ '[' 1 -ge 3 ']'
+ WHERE_DIR_GCC=/usr/bin/gcc
+ WHERE_DIR_GPP=/usr/bin/g++
+ '[' debian == centos ']'
+ '[' debian == ubuntu ']'
+ '[' debian == opensuse ']'
+ '[' '!' -d /www/server/mysql ']'
+ cd /www/server/source/mysql/mysql-8.0.28
+ cmake -DCMAKE_INSTALL_PREFIX=/www/server/mysql -DMYSQL_USER=mysql -DMYSQL_TCP_PORT=3306 -DMYSQL_UNIX_ADDR=/var/tmp/mysql.sock -DWITH_MYISAM_STORAGE_ENGINE=1 -DWITH_INNOBASE_STORAGE_ENGINE=1 -DWITH_MEMORY_STORAGE_ENGINE=1 -DENABLED_LOCAL_INFILE=1 -DWITH_PARTITION_STORAGE_ENGINE=1 -DWITH_READLINE=1 -DEXTRA_CHARSETS=all -DDEFAULT_CHARSET=utf8mb4 -DDEFAULT_COLLATION=utf8mb4_general_ci -DDOWNLOAD_BOOST=1 -DFORCE_INSOURCE_BUILD=1 -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DDOWNLOAD_BOOST=0 -DWITH_BOOST=/www/server/source/mysql/mysql-8.0.28/boost/
CMake Warning:
No source or binary directory provided.  Both will be assumed to be the
same as the current working directory, but note that this warning will
become a fatal error in future CMake releases.


-- Running cmake version 3.18.4
-- CMAKE_MODULE_PATH is /www/server/source/mysql/mysql-8.0.28/cmake
-- MySQL 8.0.28
-- Source directory /www/server/source/mysql/mysql-8.0.28
-- Binary directory /www/server/source/mysql/mysql-8.0.28
CMake Warning at CMakeLists.txt:542 (MESSAGE):
This is an in-source build


-- CMAKE_GENERATOR: Unix Makefiles
-- SIZEOF_VOIDP 8
-- Packaging as: mysql-8.0.28-Linux-x86_64
-- WITH_BOOST=/www/server/source/mysql/mysql-8.0.28/boost
-- BOOST_INCLUDE_DIR
-- LOCAL_BOOST_DIR LOCAL_BOOST_DIR-NOTFOUND
-- LOCAL_BOOST_ZIP LOCAL_BOOST_ZIP-NOTFOUND
-- Could not find (the correct version of) boost.
-- MySQL currently requires boost_1_73_0

CMake Error at cmake/boost.cmake:107 (MESSAGE):
You can download it with -DDOWNLOAD_BOOST=1 -DWITH_BOOST=<directory>

This CMake script will look for boost in <directory>.  If it is not there,
it will download and unpack it (in that directory) for you.

You can also download boost manually, from
https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.bz2


If you are inside a firewall, you may need to use an https proxy:

export https_proxy=http://example.com:80

Call Stack (most recent call first):
cmake/boost.cmake:205 (COULD_NOT_FIND_BOOST)
CMakeLists.txt:1424 (INCLUDE)


-- Configuring incomplete, errors occurred!
See also "/www/server/source/mysql/mysql-8.0.28/CMakeFiles/CMakeOutput.log".
See also "/www/server/source/mysql/mysql-8.0.28/CMakeFiles/CMakeError.log".
+ make -j3
make: *** No targets specified and no makefile found.  Stop.
+ '[' -d /www/server/mysql ']'
+ echo 安装失败
+ echo 'install fail'
install fail
+ exit 1

**Comment by RoyalSwift** [comment]
DEV没问题

> * PATH='/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin'
> * export PATH
>   ++ pwd
> * curPath=/www/server/mdserver-web/plugins/mariadb
>   ++ dirname /www/server/mdserver-web/plugins/mariadb
> * rootPath=/www/server/mdserver-web/plugins
>   ++ dirname /www/server/mdserver-web/plugins
> * rootPath=/www/server/mdserver-web
>   ++ dirname /www/server/mdserver-web
> * serverPath=/www/server
>   ++ uname
> * sysName=Linux
> * install_tmp=/www/server/mdserver-web/tmp/mw_install.pl
> * mariadbDir=/www/server/source/mariadb
> * MY_VER=10.8.3
> * action=install
> * '[' install == install ']'
> * Install_app
> * mkdir -p /www/server/source/mariadb
> * echo 正在安装脚本文件...
> * id mysql
>   ++ id -u www
> * echo 'mysql UID is 1000'
>   mysql UID is 1000
>   ++ grep '^www:' /etc/passwd
>   ++ cut -d: -f7
> * echo 'mysql Shell is /bin/bash'
>   mysql Shell is /bin/bash
> * '[' Linux '!=' Darwin ']'
> * mkdir -p /var/log/mariadb
> * touch /var/log/mariadb/mariadb.log
> * '[' -z '' ']'
> * cpuCore=1
> * '[' -f /proc/cpuinfo ']'
>   ++ cat /proc/cpuinfo
>   ++ grep processor
>   ++ wc -l
> * cpuCore=4
>   ++ free -m
>   ++ grep Mem
>   ++ awk '{printf("%.f",($2)/1024)}'
> * MEM_INFO=4
> * '[' 4 '!=' 1 ']'
> * '[' 4 '!=' 0 ']'
> * '[' 4 -gt 4 ']'
> * '[' 4 -gt 1 ']'
>   ++ echo 4
>   ++ awk '{printf("%.f",($1)*0.8)}'
> * cpuCore=3
> * '[' '!' -f /www/server/source/mariadb/mariadb-10.8.3.tar.gz ']'
> * '[' '!' -d /www/server/source/mariadb/mariadb-10.8.3 ']'
> * cd /www/server/source/mariadb
> * tar -zxvf /www/server/source/mariadb/mariadb-10.8.3.tar.gz
> 
> gzip: stdin: unexpected end of file tar: Child returned status 1 tar: Error is not recoverable: exiting now
> 
> * '[' '!' -d /www/server/mariadb ']'
> * cd /www/server/source/mariadb/mariadb-10.8.3
>   /www/server/mdserver-web/plugins/mariadb/versions/10.8/install.sh: line 71: cd: /www/server/source/mariadb/mariadb-10.8.3: No such file or directory
> * make -j3
>   make: *** No targets specified and no makefile found.  Stop.
> * '[' -d /www/server/mariadb ']'
> * echo 安装失败
> * echo 'install fail'
>   install fail
> * exit 1

**Comment by midoks** [comment]
已经合并。
