### ISSUE TITLE
流量统计区分回环流量

### ISSUE THREAD

**Issue by hi-bingo** [midoks/mdserver-web#175]
## 需求

看代码和宝塔一样使用psutil统计网卡流量，但其中包含了回环流量，对于vps服务器，是不是最好排除或者区分开这部分流量？只统计服务器对外的上下行流量？

## 提供参考
https://blog.csdn.net/u014304190/article/details/104700118
给开发者提供参考！

**Comment by midoks** [comment]
![image](https://user-images.githubusercontent.com/4169529/186061492-b4308df3-1df7-415c-986a-106d8adae452.png)

很好的意见，已经采纳。
在dev中，隔一段时间，合并到master。
