### ISSUE TITLE
安装PHP,数据库后没有增加变量

### ISSUE THREAD

**Issue by RoyalSwift** [midoks/mdserver-web#178]
-bash: mysql: command not found

安装完数据库后增加
ln -s /www/server/mysql/bin/mysql /usr/bin

**Comment by RoyalSwift** [comment]
-bash: php: command not found
php也没有增加环境变量

**Comment by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [comment]
我的也是一样

**Comment by RoyalSwift** [comment]
> 我的也是一样

给你解决方案了

**Comment by midoks** [comment]
这个手动配置吧。
