### ISSUE TITLE
debian10面板端口修改不生效及防火墙问题

### ISSUE THREAD

**Issue by yfzuix** [midoks/mdserver-web#18]
#### debian10在面板端口修改不生效
 在面板设置中修改端口后，使用新端口无法打开面板，使用安装后的默认端口可打开；重启后无论是默认端口还是新设置的端口都无法打开面板，关闭防火墙也无法打开

#### 安全-防火墙设置
打开启用防火墙开关，提示成功但貌似没生效，添加端口又提示防火墙启动时才能添加规则
![](https://s3.bmp.ovh/imgs/2022/06/11/b64498d8a888cc0e.png)

**Comment by midoks** [comment]
已经修复
