### ISSUE TITLE
关于验证码可能存在问题

### ISSUE THREAD

**Issue by neko205-mx** [midoks/mdserver-web#188]
## 什么系统 ?

Ubuntu 20.04 LTS

## 错误信息 ?

Ex:

或许验证码系统存在问题？

我敢肯定我没填写错误。。但是我不知道问题在哪。。有填写十几次了

## 错误截图 
![屏幕截图 2022-09-11 120528](https://user-images.githubusercontent.com/69409093/189511952-ee35b62d-c867-47e2-ae02-4bf929f45610.png)

![屏幕截图 2022-09-11 120543](https://user-images.githubusercontent.com/69409093/189511958-bfef5a9c-7a97-4a04-bc23-8a7ba14ac068.png)

...

## 软件版本(插件/面板) 
面板版本：0.9.9
...

**Comment by Yeche0603** [comment]
和你相同的OS和面板版本，我也遇到了一样的问题，即使是输入框均校验出现了勾的图标仍然报验证码错误。

**Comment by midoks** [comment]
经常测试，没有出现。或许是在安装过程中，有些库没有安装成.
cd /www/server/mdserver-web && pip3 install -r /www/server/mdserver-web/requirements.txt
&&
cd /www/server/mdserver-web && source bin/activate && pip3 install -r /www/server/mdserver-web/requirements.txt

**Comment by dfmjndm** [comment]
我遇到了同样的问题，问题可能来自于使用一键sh安装时的pip版本不是最新的，安装过程中确实出现了几个红色的安装错误一扫而过，但是没有终止所以也没在意。
我更新了pip，按照前文指示补充requirements，重启面板，然而验证码依然不能使用
![image](https://user-images.githubusercontent.com/57401901/196329212-8e4b0742-3b10-43e8-8154-24b29b34e1a5.png)
