### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by 1w5** [midoks/mdserver-web#197]
## 什么系统 ?
Ubuntu 20

## 错误信息 ?
·······················
patchelf is already the newest version (0.10-2build1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
./cli.sh: line 38: gunicorn: command not found
Starting mw-tasks... ./cli.sh: line 20: /www/server/mdserver-web/logs/task.log: No such file or directory
failed
------------------------------------------------------
tail: cannot open '/www/server/mdserver-web/logs/task.log' for reading: No such file or directory
------------------------------------------------------
Error: mw-tasks service startup failed.
.....................start mw fail
Time consumed: 1 Minute!
···························

**Comment by midoks** [comment]
./cli.sh: line 38: gunicorn: command not found  手动 pip install gunicorn
