### ISSUE TITLE
计划任务在创建的时候选择的分钟数不会生效，只有创建后重新编辑一下才有

### ISSUE THREAD

**Issue by qingee** [midoks/mdserver-web#201]
## 什么系统 ?

Debian 11

## 错误信息 ?
计划任务在创建的时候选择的分钟数不会生效，只有创建后重新编辑一下才有
Ex:
```bash
................start mw success
bash: line 149: ./scripts/init.d/mw: No such file or directory
```

## 错误截图 ?

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?
0.9.10.1 
...

**Comment by midoks** [comment]
已经解决，且已发布新版本。
