### ISSUE TITLE
求大佬支持面板域名和SSL

### ISSUE THREAD

**Issue by cyril-cheng** [midoks/mdserver-web#203]
## 需求
大佬，什么时候能支持面板域名和SSL啊？

**Comment by msycn** [comment]
面板新建一个二级域名网站，反向代理到http://127.0.0.1:面板端口

**Comment by midoks** [comment]
0.9.13 加了。去测试一下，有什么问题？再说吧。

**Comment by cyril-cheng** [comment]
首先感谢大佬的支持，最近给面板升级到了最新版，然后用acme给面板颁发了ssl证书，并且在面板设置里面开启了面板ssl开关。但是重载mw进程，刷新浏览器以后报错，显示：此网站无法提供安全连接  ERR_SSL_PROTOCOL_ERROR。
