### ISSUE TITLE
服务器ssh 重启后,启动面板报错, 其余php数据库服务正常

### ISSUE THREAD

**Issue by msycn** [midoks/mdserver-web#204]
## 什么系统 ?

Ubuntu 22.04?

## 错误信息 ?
Stack trace:
#0 {main}
  thrown in /www/wwwroot/cnflix.com/artisan on line 18
root@naifeis:/www/wwwroot/cnflix.com# ^C
root@naifeis:/www/wwwroot/cnflix.com# service mw status
● mw.service - LSB: starts mw
     Loaded: loaded (/etc/init.d/mw; generated)
     Active: active (running) since Wed 2022-10-05 20:35:56 EDT; 3min 1s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 842 ExecStart=/etc/init.d/mw start (code=exited, status=0/SUCCESS)
      Tasks: 6 (limit: 28701)
     Memory: 72.1M
        CPU: 2.631s
     CGroup: /system.slice/mw.service
             ├─871 /bin/bash /etc/init.d/mw start
             └─873 python3 task.py

Oct 05 20:35:56 naifeis mw[1377]: [2022-10-05 19:55:04 -0400] [1155] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
Oct 05 20:35:56 naifeis mw[1377]: [2022-10-05 19:55:04 -0400] [1264] [INFO] Booting worker with pid: 1264
Oct 05 20:35:56 naifeis mw[1377]: [2022-10-05 19:55:04 -0400] [1267] [INFO] Booting worker with pid: 1267
Oct 05 20:35:56 naifeis mw[1377]: /www/server/mdserver-web/app.py:9: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead >Oct 05 20:35:56 naifeis mw[1377]:   monkey.patch_all()
Oct 05 20:35:56 naifeis mw[1377]: [2022-10-05 20:35:50 -0400] [1185] [INFO] Starting gunicorn 20.1.0
Oct 05 20:35:56 naifeis mw[1377]: Error: Already running on PID 1155 (or pid file '/www/server/mdserver-web/logs/mw.pid' is stale)
Oct 05 20:35:56 naifeis systemd[1]: Started LSB: starts mw.
Oct 05 20:35:56 naifeis mw[842]: ------------------------------------------------------
Oct 05 20:35:56 naifeis mw[842]: Error: mw-panel service startup failed.

## 错误截图 ?

...

## 浏览器版本 ?

...Edge 106

## 软件版本(插件/面板) ?

php 8.1 + OpenResty 1.21.

**Comment by msycn** [comment]
定位到 /www/server/mdserver-web/logs/mw.pid 被占用,

只要删除, service mw restart  就恢复正常. 目前没有影响

**Comment by msycn** [comment]
正常后的日志
root@naifeis:/www/wwwroot/cnflix.com# rm /www/server/mdserver-web/logs/mw.pid
root@naifeis:/www/wwwroot/cnflix.com# service mw restart
root@naifeis:/www/wwwroot/cnflix.com# service mw status
● mw.service - LSB: starts mw
     Loaded: loaded (/etc/init.d/mw; generated)
     Active: active (running) since Wed 2022-10-05 20:46:54 EDT; 4s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1534 ExecStart=/etc/init.d/mw start (code=exited, status=0/SUCCESS)
      Tasks: 11 (limit: 28701)
     Memory: 91.3M
        CPU: 1.671s
     CGroup: /system.slice/mw.service
             ├─1540 /bin/bash /etc/init.d/mw start
             ├─1542 python3 task.py
             ├─1570 /www/server/mdserver-web/bin/python3 /www/server/mdserver-web/bin/gunicorn -c setting.py app:app
             ├─1627 /www/server/mdserver-web/bin/python3 /www/server/mdserver-web/bin/gunicorn -c setting.py app:app
             └─1629 /www/server/mdserver-web/bin/python3 /www/server/mdserver-web/bin/gunicorn -c setting.py app:app

Oct 05 20:46:50 naifeis systemd[1]: Starting LSB: starts mw...
Oct 05 20:46:51 naifeis mw[1534]: Starting mw-tasks... done
Oct 05 20:46:54 naifeis mw[1534]: Starting mw-panel... ...done
Oct 05 20:46:54 naifeis systemd[1]: Started LSB: starts mw.

**Comment by midoks** [comment]
优化了。

**Comment by msycn** [comment]
> 优化了。

感谢大佬
