### ISSUE TITLE
日志切割失败，name 'reload' is not defined

### ISSUE THREAD

**Issue by sirfromprc** [midoks/mdserver-web#206]
## 什么系统 ?

 Centos 8

## 错误信息 ?

 File "/www/server/mdserver-web/scripts/logs_backup.py", line 18, in <module>
    reload(sys)
NameError: name 'reload' is not defined

## 软件版本(插件/面板) ?
0.9.12
...
python3里面 
reload(sys)
sys.setdefaultencoding('utf-8')
这两句是不是要改为
import importlib,sys 
importlib.reload(sys)

我改了后就成功了

**Comment by sirfromprc** [comment]
另外日志再安全处手工清除后，就不会再产生网站日志，除非到网站的配置文件处重新保存一下，才会重新生成日志

**Comment by midoks** [comment]
已优化
