### ISSUE TITLE
安装Redis 插件后,php实际没有激活

### ISSUE THREAD

**Issue by msycn** [midoks/mdserver-web#207]
## 什么系统 ?

 Ubuntu 22.04?

## 错误信息 ?

安装Redis 插件后,实际没有激活

## 错误截图 ?
![网页捕获_9-10-2022_213443_130 162 157 37](https://user-images.githubusercontent.com/85003651/194789221-2f680263-5994-405b-9171-67c5a0049086.jpeg)

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

Redis 7.0.4

**Comment by msycn** [comment]
需打开php的配置文件php.ini，修改下面的配置：
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379"
;如果你设置了redis密码，则用下面整个配置
;session.save_path = "tcp://127.0.0.1:6379?auth=密码"

**Comment by midoks** [comment]
0.9.13 添加会话管理 用与调整。
