### ISSUE TITLE
总体很不错，提几个小问题

### ISSUE THREAD

**Issue by feyanru** [midoks/mdserver-web#211]
## 什么系统 ?

centos8

## 错误信息 ?

1、php56装memcached扩展提示出错，memcache没问题，正常使用。出错log
checking for libmemcached location... configure: error: memcached support requires libmemcached. Use --with-libmemcached-dir=<DIR> to specify the prefix where libmemcached headers and library are located
make: *** No rule to make target 'clean'.  Stop.
ERROR!
cd /www/server/mdserver-web/plugins/php/versions/common && bash memcached.sh install 56
cd /www/server/mdserver-web/plugins/php/versions/56 && bash memcached.sh install 56
cd /www/server/mdserver-web/plugins/php/versions/common && bash memcached.sh uninstall 56
cd /www/server/mdserver-web/plugins/php/versions/56 && bash memcached.sh uninstall 56

php56会话管理里面的存储模式设为memcache的时候 php配置文件里session.save_handler = memcache 这句没加上，导致下次再进会话管理的时候里面存储模式为files

2、phpmyadmin安全设置处修改端口保存后当前用修改后的端口能打开，一旦停止phpmyadmin后，再重启phpmyadmin端口又变为888，需要手工再次改变。

## 软件版本(插件/面板) ?
0.9.13

mdserver-web相当不错，老大辛苦了

**Comment by midoks** [comment]
1.没有遇到，一起正常。
2.已经优化，需要执行 mw update_dev 。 更新代码
