### ISSUE TITLE
遇到的几个小问题

### ISSUE THREAD

**Issue by notetoday** [midoks/mdserver-web#212]
1、在文件界面上传压缩包后进行解压不能覆盖已存在的同名文件夹及文件。
2、文件目录界面右键点击呼出菜单会出现不能呼出菜单失灵状况，或者菜单出现后会出现错位，出现在最底部无法进行选择。
3、在安装Mysql的时候会检测swap插件的安装情况，如果没有安装swap则无法安装数据库，如果安装swap是强制性操作，请把swap在安装面板的时候就进行默认安装。

**Comment by midoks** [comment]
0.11.0 has been basically optimized。
