### ISSUE TITLE
OP防火墙启动失败

### ISSUE THREAD

**Issue by dfmjndm** [midoks/mdserver-web#213]
## 什么系统 ?
Centos 7

## 错误信息 ?
OP防火墙启动失败

## 错误截图 ?
![image](https://user-images.githubusercontent.com/57401901/196082652-1c74f9e6-2649-42f1-98fc-e027eb95f44c.png)

## 浏览器版本 ?
Chrome-latest

## 软件版本(插件/面板) ?
latest

在之前issue中有人表示重启面板可以解决这个问题，尝试后未能解决。

**Comment by midoks** [comment]
卸载重装，， 用新版本，已更新。
