### ISSUE TITLE
openresty 1.21 内嵌nginx也是1.21，请问是否会有漏洞影响。

### ISSUE THREAD

**Issue by linuxxx** [midoks/mdserver-web#215]
openresty 1.21 内嵌nginx也是1.21，请问是否会有漏洞影响。
TGqun无法加入，提示被封禁或者不存在。

**Comment by midoks** [comment]
TG:你没有验证通过。 账号。 我找你了那个叫0day的问题。12.4说以下有这个问题。 openresty没有特别说明，我也不清楚。 等版本更新后，我第一时间更新版本吧。
