### ISSUE TITLE
在申请ssl的证书时出现的问题 

### ISSUE THREAD

**Issue by a55431** [midoks/mdserver-web#217]
## 什么系统 ?

Centos 7.8

## 错误信息 ?

大牛还是上次提的那个SSL申请问题。尝试了多次 还是总是失败，但是在WEB目录下也获取到了验证文件，在ACME.SH目录下也建立了域名的文件夹，但是获取不到最后的CA证书。域名解析过来已经十多天了。不存在DNS验证不通过，在国内腾讯云，香港的华为云，均遇到这样的情况，偶尔一次会申请成功，具体成功和失败的原因不知道是哪里问题。在用宝塔，小皮去测试的时候不会出现这种问题。zerossl里边也没有申请的记录，成功获取到的就会有。

## 错误截图 ?
![1](https://user-images.githubusercontent.com/116335044/197394079-85cd5209-a629-4647-8e1c-a8f4b5934d37.png)
![2](https://user-images.githubusercontent.com/116335044/197394097-3a39bf4d-e85c-4bca-b2ac-c28dbb8b26c3.png)
![3](https://user-images.githubusercontent.com/116335044/197394113-af64e396-e836-4908-8e2c-4be2568e78fb.png)

>

**Comment by a55431** [comment]
或者您们没有遇到相同的问题吗？

**Comment by midoks** [comment]
你tg账户，我需要在线测试看看问题。

**Comment by a55431** [comment]
我回复邮件因为有隐私问题,Issues我删除了，我在回复的时候抄送了一份给您midoks@163.com邮箱

**Comment by a55431** [comment]
您好，刚才我登录服务器发现已经安装mdserver,您是否发现ssl申请有问题，我陈述的问题复现了吗？是服务器的问题，还是acme的问题，还是咱们mdserver的问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "8948989"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 晚上8:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [midoks/mdserver-web] 在申请ssl的证书时出现的问题  (Issue #217)



我没有TG账户，我可以给您提供一台华为云香港服务器，我刚才测试了小皮，小皮已经没有使用acme.sh，宝塔我在正常使用。
咱们的MDSERVER我换了个域名去测试自动申请ssl同样的问题复现,不知道成功和失败条件具体取决于哪里。大神看看哪里的问题，希望我们的mdserver越来越好。


119.8.25.50
root&nbsp; 密码 MD-server




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "midoks/mdserver-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [midoks/mdserver-web] 在申请ssl的证书时出现的问题  (Issue #217)





 
你tg账户，我需要在线测试看看问题。

**Comment by Acer-bdog** [comment]
同问，我也是一直申请不下来
