### ISSUE TITLE
添加计划任务报错:分钟数不能为空

### ISSUE THREAD

**Issue by msycn** [midoks/mdserver-web#229]
## 什么系统 ?

Ubuntu 22.04

## 错误信息 ?

添加计划任务 执行周期 N分钟 报错:分钟数不能为空
## 错误截图 ?

![网页捕获_30-10-2022_212459_193 122 108 50](https://user-images.githubusercontent.com/85003651/198913279-44a9cc7f-a0e9-447c-8ba0-44885b678634.jpeg)

## 浏览器版本 ?

Edge 107

## 软件版本(插件/面板) ?
0.10.2

**Comment by midoks** [comment]
js问题，已经修复。
