### ISSUE TITLE
debian11 使用升级命令后，mw出错

### ISSUE THREAD

**Issue by PeroPer0** [midoks/mdserver-web#234]
## 什么系统 ?
debian11 

## 错误信息 ?
0.10.1使用升级命令到0.10.2后，mw命令后，显示错误

## 错误截图 

root@debian:~# mw
===============mdserver-web cli tools=================
Traceback (most recent call last):
  File "/www/server/mdserver-web/tools.py", line 156, in <module>
    mwcli(clinum)
  File "/www/server/mdserver-web/tools.py", line 36, in mwcli
    print("(1) \u91cd\u542f\u9762\u677f\u670d\u52a1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 4-9: ordinal not in range(256)

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

...

**Comment by midoks** [comment]
export LC_ALL=en_US.UTF-8

再执行看看。

**Comment by PeroPer0** [comment]
可以了，原来是这个问题
