### ISSUE TITLE
mysql管理密码修复失败

### ISSUE THREAD

**Issue by q27598** [midoks/mdserver-web#247]
## 什么系统 ?

Debian 11
## 错误信息 ?
点修复 修复成功但是还是显示修复

**Comment by midoks** [comment]
已优化

**Comment by hang666** [comment]
mariadb也修复失败 依旧密码错误

**Comment by midoks** [comment]
> mariadb也修复失败 依旧密码错误

在tg群，私，我需要服务器，针对性解决。。
