### ISSUE TITLE
网站统计app 0.2.2 没有数据

### ISSUE THREAD

**Issue by tomlei88** [midoks/mdserver-web#249]
## 什么系统 ?

CentOS Linux 7.8.2003 (Core)　

## 错误信息 ?

感谢大佬开发的面板，麻烦看看 网站统计app 0.2.2 没有数据

## 错误截图 ?

![360截图20221105224800141](https://user-images.githubusercontent.com/103014450/200125780-4fa98ebc-dc44-4ec5-b283-f72379cfd60b.jpg)

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

0.10.2

**Comment by midoks** [comment]
已经优化
