### ISSUE TITLE
frps插件

### ISSUE THREAD

**Issue by mymine** [midoks/mdserver-web#261]
## 需求
frps插件

## 提供参考

给开发者提供参考！

**Comment by midoks** [comment]
https://github.com/mw-plugin/frp
写了个简版的，将就用吧。

**Comment by mymine** [comment]
> https://github.com/mw-plugin/frp 写了个简版的，将就用吧。
 @midoks 有两个模板
https://github.com/Xeath/btp_frps
https://github.com/sang8052/btpanel_frps
