### ISSUE TITLE
点击插件安装无反应

### ISSUE THREAD

**Issue by 8ty** [midoks/mdserver-web#265]
## 什么系统 ?

Ubuntu 22

## 错误信息 ?

Ex:
```bash
................start mw success
bash: line 149: ./scripts/init.d/mw: No such file or directory
```

## 错误截图 ?

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

...
最新的

**Comment by 8ty** [comment]
以及上传界面 出错
![image](https://user-images.githubusercontent.com/92656899/202943427-80c7aa51-5be0-4314-8c9a-4b00243dbf3d.png)

**Comment by midoks** [comment]
经测试，无问题。
怀疑是网速问题。js或css未加载。刷新或重启。
