### ISSUE TITLE
定时任务中获取数据库列表失败

### ISSUE THREAD

**Issue by TwooSix** [midoks/mdserver-web#272]
## 什么系统 ?

Debian 11

## 错误信息 ?

列表为空

## 错误截图 ?

![image](https://user-images.githubusercontent.com/62167519/204123942-94b5d6db-3267-4347-a938-babf300b0f74.png)

## 软件版本(插件/面板) ?

面板：11.0
数据库：MariaDB 10.9

**Comment by midoks** [comment]
MariaDB 暂时不在计划任务里。
