### ISSUE TITLE
可以添加磁盘管理插件吗？

### ISSUE THREAD

**Issue by mymine** [midoks/mdserver-web#273]
## 需求
手动挂载太麻烦了！BT面板有这个插件。可以开发磁盘管理插件吗？
管理磁盘，挂载，卸载，格式化磁盘，挂载smb和webdav等功能。

## 提供参考

给开发者提供参考！

**Comment by midoks** [comment]
是那个插件，没有找到。

**Comment by mymine** [comment]
> 是那个插件，没有找到。

宝塔里有个磁盘管理插件。好久没用了，没有了吗

**Comment by midoks** [comment]
没有，就算了。
