### ISSUE TITLE
安装失败。

### ISSUE THREAD

**Issue by mymine** [midoks/mdserver-web#279]
## 什么系统 ?

Ubuntu 18

## 错误信息 ?
(https://user-images.githubusercontent.com/2943365/204430279-8876b180-f942-48ff-b380-58303f97555f.jpg)

ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

lib ok!
cli.sh: line 38: gunicorn: command not found
Starting mw-tasks... cli.sh: line 20: /www/server/mdserver-web/logs/task.log: No such file or directory
failed
------------------------------------------------------
tail: cannot open '/www/server/mdserver-web/logs/task.log' for reading: No such file or directory
------------------------------------------------------
Error: mw-tasks service startup failed.
.....................start mw fail
```

## 错误截图 ?
(https://user-images.githubusercontent.com/2943365/204430279-8876b180-f942-48ff-b380-58303f97555f.jpg)
...


## 浏览器版本 ?

...


## 软件版本(插件/面板) ?

...

**Comment by midoks** [comment]
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device.
哥子，很明显的错误，硬盘不够用了。

**Comment by mymine** [comment]
> 

/目录30G。/data 20G

**Comment by midoks** [comment]
你搞个纯净一点的环境吧。
