### ISSUE TITLE
修改 pip的源  老是超时安装错误

### ISSUE THREAD

**Issue by leeaikong** [midoks/mdserver-web#281]
报错
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=‘files.pythonhosted.org’, port=443): Read timed out.

目前解决方法 
ETC目录新增 pip.conf文件
[global]
trusted-host=mirrors.aliyun.com
index-url=http://mirrors.aliyun.com/pypi/simple/

安装命令里 可否直接修改为阿里云或者国内其他源？

**Comment by midoks** [comment]
你是国内的服务器，还是国外的服务器。

**Comment by leeaikong** [comment]
> 

本地电脑  wsl 子系统安装的，   
国内网络

**Comment by midoks** [comment]
curl -fsSL  https://raw.githubusercontent.com/midoks/mdserver-web/dev/scripts/install_dev.sh | bash
执行这个开发的，测试一下，通过后，关闭。过段时间，合并到主分支。

**Comment by leeaikong** [comment]
修改源以后  到最后一步 提示安装成功，但是还是启动不了 服务

**Comment by midoks** [comment]
未有wsl环境，无法测试。如有讨论，到TG吧，我先睡了。
