### ISSUE TITLE
安装PHP82失败

### ISSUE THREAD

**Issue by c90c90** [midoks/mdserver-web#283]
## 什么系统 ?

Ubuntu 22.04.1 LTS　

## 错误信息 ?

安装PHP82，第一次运行1分10秒结束（安装php74耗时16分钟），消息盒子提示已完成，应用列表对应PHP82无变化，操作列仍是安装，再次点击安装，消息盒子提示0分0秒已完成，仍然无变化

## 错误截图 ?

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

0.11.2

**Comment by midoks** [comment]
已修复。
