### ISSUE TITLE
修改数据库密码大概率报错['InternalError' object is not iterable]!

### ISSUE THREAD

**Issue by c90c90** [midoks/mdserver-web#284]
## 什么系统 ?

Ubuntu 22.04 LTS　

## 错误信息 ?
mysql-管理列表-改密时大概率失败报错：
修改数据库xx密码失败['InternalError' object is not iterable]!

更新：进入phpmyadmin发现新建的数据库不存在，重启面板无法解决，重启服务器后进行修复可在phpmyadmin中看到数据库

## 软件版本(插件/面板) ?

0.11.2

**Comment by midoks** [comment]
mysql几？

**Comment by midoks** [comment]
经测试，没有问题。
用mw update_dev 更新一下吧。估计python的库版本没有兼容。。此自动安装合适的库。
