### ISSUE TITLE
UI方面的bug

### ISSUE THREAD

**Issue by c90c90** [midoks/mdserver-web#285]
## 什么系统 ?

ubuntu 22.04.1LTS

## 错误信息 ?

1.文件管理页面中目录栏手动输入多个/并敲回车后UI显示异常
![image](https://user-images.githubusercontent.com/17155084/205923112-c43d0005-5826-4a10-abc4-b16f96c05586.png)
![image](https://user-images.githubusercontent.com/17155084/205923147-f6a9248c-4396-432a-adcb-44c3787201bb.png)
![image](https://user-images.githubusercontent.com/17155084/205923522-c675d779-ab1d-433e-8d34-2d47b6d7af7f.png)
![image](https://user-images.githubusercontent.com/17155084/205923539-c4663cba-4826-43db-8d35-3a54856af60a.png)

2.重命名文件时保存按钮疑似实际为取消按钮的作用

3.重命名后点击完成按钮提示的是：移动文件或目录成功!

## 软件版本(插件/面板) ?

0.11.2

**Comment by midoks** [comment]
观察细致入微。已优化。 👍
