### ISSUE TITLE
查看面板信息 密码不能正确显示的 BUG

### ISSUE THREAD

**Issue by leeaikong** [midoks/mdserver-web#288]
最新 11.3
通过ssh修改 面板密码以后

输入  mw 10 查看面板信息

面板的密码没变化。 不是新改的密码 （修改用户名后，可以正确显示）

看图片 修改密码后 查看面板信息 还是以前的密码

![QQ截图20221209143131](https://user-images.githubusercontent.com/40814658/206639600-7d65e9eb-92d5-4752-923d-a1815b6b631b.png)

**Comment by midoks** [comment]
这不是bug，修改密码后，不会显示了，防止密码泄露。

**Comment by leeaikong** [comment]
那我觉得 应该在 password处 不要显示密码了。 显示文字  忘记密码重新修改之类的

这样会误导 我刚才一直用错误的密码登录了好多次 才想起来修改密码

**Comment by midoks** [comment]
嗯，我以后优化一下。
