### ISSUE TITLE
SSH UI 显示错误

### ISSUE THREAD

**Issue by Torther** [midoks/mdserver-web#295]
## 什么系统 ?

Ubuntu 22.04.1 LTS

## 错误信息 ?

SSH UI 显示错误

## 错误截图 ?

![Snipaste_2022-12-11_21-47-35](https://user-images.githubusercontent.com/29655416/206907467-3e2bc194-8329-4d4d-b4a9-02338db17863.png)

## 浏览器版本 ?

Microsoft Edge
版本 110.0.1543.0 (正式版本) dev (64 位)

## 软件版本(插件/面板) ?

0.11.41670766240.624653

**Comment by midoks** [comment]
我在最新版测试没有问题。你先更新最新版试一试吧。
