### ISSUE TITLE
面板安装imail的时候系统架构识别有问题

### ISSUE THREAD

**Issue by xiaonian233** [midoks/mdserver-web#301]
## 什么系统 ?

Debian 10 Arm64

## 错误信息 ?

```
安装imail后一直启动不起来，查看安装日志发现在判断系统架构的时候出了问题，get到了aarch64但是下载出来的版本是amd64
```

## 错误截图 ?
![image](https://user-images.githubusercontent.com/21072615/207274452-e96cce86-7a81-4497-972c-eaba47ee8808.png)

## 软件版本(插件/面板) ?
```
imail是0.0.19
面板是0.11.4

**Comment by midoks** [comment]
开发版，已经解决。
