### ISSUE TITLE
OpenResty 不能反代ipv6地址

### ISSUE THREAD

**Issue by james20226** [midoks/mdserver-web#303]
## 什么系统 ?

Debian 11

## 错误信息 ?

Ex:
```bash
................start mw success
bash: line 149: ./scripts/init.d/mw: No such file or directory
```

## 错误截图 ?

错误的目标地址!

## 浏览器版本 ?

chrome

## 软件版本(插件/面板) ?

今天刚更新的

**Comment by james20226** [comment]
希望编译的时候加上 --with-ipv6 参数 让OpenResty支持ipv6

**Comment by midoks** [comment]
![image](https://user-images.githubusercontent.com/4169529/208254405-d30879c4-d6e7-4a4f-92d5-c499c33dd608.png)
早已存在，检查自己的配置，是否正确。
