### ISSUE TITLE
ftp备份网站有点问题

### ISSUE THREAD

**Issue by feyanru** [midoks/mdserver-web#307]
## 什么系统 ?

 Centos 7 最新dev

## 错误信息 ?
1、计划任务网页备份、切割日志添加后不能编辑，数据库可以
2、网页ftp备份不能执行，数据库可以ftp备份，本地存储均没问题
3、FTP存储空间如果不是默认21端口，用192.168.1.12:1235 基本添加不上服务器，源码改默认端口号可以添加上账户。

旧版本是没问题的。

## 错误截图 ?

/www/backup/site/web_192.168.1.12_20221219_033703.tar.gz
★[2022/12/19 03:37:05] 网站[192.168.1.12]备份成功,用时[2.31]秒
|---保留最新的[3]份备份
|---文件名:/www/backup/site/web_192.168.1.12_20221219_033703.tar.gz
|---已清理过期备份文件：/www/backup/site/web_192.168.1.12_20221219_022950.tar.gz
not find upload file!
False

**Comment by feyanru** [comment]
升级了下，现在添加备份网站时无法选择“FTP存储空间”
另外还是不能ftp备份上传，好像backup_ftp/index.py 中
    if stype == 'database':
        bk_prefix = prefix_dict[stype]
    else:
        plugin_name = stype.replace('database_', '')
        bk_prefix = plugin_name + '/db'
这段可能有问题。 改成if stype != 'database': 好像就可以了

**Comment by midoks** [comment]
我又优化了一下。你再试试。

**Comment by feyanru** [comment]
十分感谢，1、2可以了没问题。另外我在ftp_client.py 中   
     if host.find(':') == -1:
            self.__port = self.default_port
后加了
        else:
            self.__host = host.split(':')[0]
            self.__port = host.split(':')[1]
原来的self.__host = data['ftp_host'].strip()放到前面去了。
就可以用192.168.1.12:1235 这种方式添加服务器了。麻烦你修复下，省的每次都要手工调整。

**Comment by midoks** [comment]
可以。

**Comment by feyanru** [comment]
重装ftp存储空间发现192.168.1.12:1235  无法写入json文件，提示失败，原来192.168.1.12:1235 被切割成了192.168.1.12。把t = args[i].split(':')改成了t = args[i].split(':',1)这下彻底没问题了。
