### ISSUE TITLE
面板ssl开关无效

### ISSUE THREAD

**Issue by cyril-cheng** [midoks/mdserver-web#308]
问题描述：

首先感谢大佬的支持，最近给面板升级到了最新版，然后用acme给面板颁发了ssl证书，并且在面板设置里面开启了面板ssl开关。但是重载mw进程，刷新浏览器以后报错，显示：此网站无法提供安全连接  ERR_SSL_PROTOCOL_ERROR。
## 什么系统 ?

debian11

## 错误信息 ?

此网站无法提供安全连接  ERR_SSL_PROTOCOL_ERROR。

## 错误截图 ?

...
![image](https://user-images.githubusercontent.com/49748357/208391291-8469faec-e87a-4e81-9be1-e7fde55b3b48.png)

## 浏览器版本 ?

...chrome 108.0

## 软件版本(插件/面板) ?

...mw 0.11.4

**Comment by cyril-cheng** [comment]
![image](https://user-images.githubusercontent.com/49748357/208567628-6cefa3ef-234a-4cc7-b01d-60a4455fc04e.png)
![image](https://user-images.githubusercontent.com/49748357/208567734-6e871678-eb52-4602-9441-fdd61d7487f1.png)

**Comment by xh0028** [comment]
最新版0.12.0, 一模一样的问题.

**Comment by jxjeff** [comment]
最新版 0.12.0, 同样出现该问题.

**Comment by midoks** [comment]
已经优化。请尝鲜。
