### ISSUE TITLE
面板登录安全问题

### ISSUE THREAD

**Issue by illuz** [midoks/mdserver-web#309]
## 什么系统 ?

Debian 11

## 错误信息 ?

无

## 错误截图 ?

无

## 浏览器版本 ?

无

## 软件版本(插件/面板) ?

最新面板

## 问题描述

这边在登录时会临时往 data/api_login.txt 写入用户名：

https://github.com/midoks/mdserver-web/blob/master/route/__init__.py#L339

然后再下次 checkLogin 时把文件读出来用并删除：

https://github.com/midoks/mdserver-web/blob/master/route/__init__.py#L189

这个功能应该是给其它面板入口用来应对跨域登录的（？），但却对面板安全性带来很严重的问题：
**checkLogin 那边，会判断如果用户登录了就 return True，没登录的话，会走到下面的逻辑，读取 data/api_login.txt 并把 username 拿出来设置登录状态到 session 中。**

**这样会导致我登录过后会产生 data/api_login.txt，而且我当前一直是登录状态，不会走到下面的删除文件的逻辑，其它用户再打开面板时，一旦触发 checkLogin，就会自动变成登录状态，而且是没有 overdue 的那种！**

这差不多就是祼奔了吧！

## 建议解决方式

- 暂时不要提供其它面板自动登录功能，直到设计一个比较安全的认证传递方式

**Comment by illuz** [comment]
重现步骤：
在浏览器 A 登录后，用浏览器 B 打开，多刷新几次，就能进入面板并获得不会过期的 session。

**Comment by NMSLSE** [comment]
我糙，我也复现了，太吓人
