### ISSUE TITLE
消息盒子错误返回

### ISSUE THREAD

**Issue by fengguowudi** [midoks/mdserver-web#312]
## 什么系统 ?

Debian11

## 错误信息 ?

消息盒子显示PHP7.4已安装完成，但是实际并未安装成功

## 错误截图 ?

![image](https://user-images.githubusercontent.com/55879152/209030224-153dbd35-4fff-4187-a0d3-0f0139a13e38.png)
![image](https://user-images.githubusercontent.com/55879152/209030261-ec1a0239-ac33-4d24-a72a-4730a0dc2106.png)

## 浏览器版本 ?

Edge/108.0.1462.46

## 软件版本(插件/面板) ?

面板0.12.0

**Comment by fengguowudi** [comment]
建议若安装失败，直接返回失败log（

**Comment by fengguowudi** [comment]
![image](https://user-images.githubusercontent.com/55879152/209031002-5b1335e0-5833-4548-996c-f297b3c312d0.png)
![image](https://user-images.githubusercontent.com/55879152/209031016-4ea0a357-6555-4981-a815-70a6d6240df1.png)
Mysql情况一致

**Comment by fengguowudi** [comment]
重新第二次安装，显示安装成功，目前尚不知晓如何复现

**Comment by shaozi17** [comment]
你可以贴一下失败日志

**Comment by fengguowudi** [comment]
> 你可以贴一下失败日志

他显示成功，我哪来的失败日志

**Comment by shaozi17** [comment]
呃,我指的是执行日志

**Comment by shaozi17** [comment]
位置应该在/www/server/mdserver-web/logs 你可以找找看有没有

**Comment by fengguowudi** [comment]
> 位置应该在/www/server/mdserver-web/logs 你可以找找看有没有

/www/server/mdserver-web/app.py:30: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/www/server/mdserver-web/lib/python3.9/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/www/server/mdserver-web/lib/python3.9/site-packages/urllib3/util/__init__.py)']. 
  monkey.patch_all()
[2022-12-22 10:16:46 +0800] [38521] [INFO] Starting gunicorn 20.1.0
[2022-12-22 10:16:46 +0800] [38521] [INFO] Listening at: http://0.0.0.0:45258 (38521)
[2022-12-22 10:16:46 +0800] [38521] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2022-12-22 10:16:46 +0800] [38590] [INFO] Booting worker with pid: 38590

**Comment by fengguowudi** [comment]
只有这一句
其他文件都是空的

**Comment by midoks** [comment]
看执行日志
