### ISSUE TITLE
添加子域名做为网站删除后，在绑定子目录添加同样的网站报错

### ISSUE THREAD

**Issue by ramondelee** [midoks/mdserver-web#314]
在网站那里添加aaa.com后，添加bbs.aaa.com，后来删除bbs.aaa.com在绑定子域名添加bbs.aaa.com，一直报错"该网站已存在”

**Comment by ramondelee** [comment]
0.12版本，重新用Ubuntu18重新安装，了目录绑定报如下错误
nginx: [emerg] open() "/www/server/openresty/nginx/conf/enable-php-56.conf" failed (2: No such file or directory) in /www/server/web_conf/nginx/vhost/xaoyo.net.conf:78
nginx: configuration file /www/server/openresty/nginx/conf/nginx.conf test failed

**Comment by midoks** [comment]
已经修复
