### ISSUE TITLE
能否增加类似宝塔的免费NGINX防火墙？

### ISSUE THREAD

**Issue by kingmo888** [midoks/mdserver-web#319]
## 需求

想开发一个什么插件?
防火墙插件
想有什么功能?
防CC，禁IP访问等。

## 提供参考
宝塔免费nginx防火墙

给开发者提供参考！

**Comment by cyril-cheng** [comment]
不是有吗？

**Comment by midoks** [comment]
有一个插件叫【OP防火墙】，多翻翻
