### ISSUE TITLE
安装成功后只有用户名没有密码

### ISSUE THREAD

**Issue by digdigdog** [midoks/mdserver-web#32]
安装成功后只有用户名没有密码，点忘记密码修改也不成功，请帮忙看下
<img width="703" alt="image" src="https://user-images.githubusercontent.com/29923302/173625636-acce0555-8955-4162-9b84-721afc5433b7.png">

**Comment by midoks** [comment]
安装没有成功！

- pip install psutil==5.9.1
or 
- curl -fsSL  https://raw.githubusercontent.com/midoks/mdserver-web/master/scripts/update.sh | bash

**Comment by digdigdog** [comment]
解决了，感谢！
