### ISSUE TITLE
网站添加额外域名时报错：访问异常:'>' not supported between instances of 'list' and 'int'!

### ISSUE THREAD

**Issue by eepicture** [midoks/mdserver-web#323]
## 什么系统 ?

Debian 11

## 错误信息 ?
在网站管理里面给网站添加额外域名时提示错误，无法添加额外域名。
提示：
访问异常:'>' not supported between instances of 'list' and 'int'!

## 错误截图 ?

![图片](https://user-images.githubusercontent.com/46742376/210776159-d4c57bb5-5b35-4b7b-b4d5-34e0fd7ff524.png)

## 浏览器版本 ?

firefox esr 85

## 软件版本(插件/面板) ?

0.12.1

**Comment by midoks** [comment]
这个已经解决，感谢及时指出。 mw update,更新即可。关于防火墙。我centos7测试了一下，OK的。你什么系统。或者tg联系我解决。
