### ISSUE TITLE
网站统计插件不可用

### ISSUE THREAD

**Issue by eepicture** [midoks/mdserver-web#326]
## 什么系统 ?

Debian 11, Centos 7.9

## 错误信息 ?

Ex:
网站统计插件不可用

## 错误截图 ?

![图片](https://user-images.githubusercontent.com/46742376/210918689-0bb91692-4c53-490a-aa23-63512f8f1b4f.png)

## 浏览器版本 ?

firefox esr 85

## 软件版本(插件/面板) ?

0.2.2

**Comment by midoks** [comment]
重启一下，试试。

**Comment by eepicture** [comment]
不行，尝试了服务重启、面板重启、服务器重启，统计信息还是全0

**Comment by midoks** [comment]
> 不行，尝试了服务重启、面板重启、服务器重启，统计信息还是全0

tg：call me.

**Comment by eepicture** [comment]
我的错，需要先更新面板，重启服务才可以统计。
不过又发现个问题，在“网站列表”-“设置”里面删除排除项后保存不生效。
![图片](https://user-images.githubusercontent.com/46742376/210954486-2fb53353-7704-4849-bbc4-2f805e802494.png)

**Comment by eepicture** [comment]
又发现个问题，静态网站没有统计信息。

**Comment by midoks** [comment]
> 又发现个问题，静态网站没有统计信息。

是这样的，现在，添加一个站点，需要重启网站统计，才能起效。你试一试。

**Comment by xiaomoy** [comment]
dev重启没用
```
2023/01/11 17:28:03 [error] 293577#0: *75 lua entry thread aborted: runtime error: /www/server/webstats/lua/webstats_common.lua:628: attempt to index local 'update_stat_stmt' (a nil value)
stack traceback:
coroutine 0:
	/www/server/webstats/lua/webstats_common.lua: in function '_update_stat_pre'
	/www/server/webstats/lua/webstats_common.lua:285: in function </www/server/webstats/lua/webstats_common.lua:233>, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:80
```
