### ISSUE TITLE
php8.2无sg11扩展

### ISSUE THREAD

**Issue by xiaomoy** [midoks/mdserver-web#335]
## 什么系统 ?

Debian 11

## 错误信息 ?

php8.2无sg11扩展
![image](https://user-images.githubusercontent.com/43872911/211745281-ee5710d0-5447-481d-9677-bd4c89e60190.png)

```bash
debian:11
cp: cannot stat '/www/server/source/php/php_lib/sg11/linux-x86_64/ixed.8.2.lin': No such file or directory
ERROR!
cd /www/server/mdserver-web/plugins/php/versions/common && bash sg11.sh install 82
cd /www/server/mdserver-web/plugins/php/versions/82 && bash sg11.sh install 82
cd /www/server/mdserver-web/plugins/php/versions/common && bash sg11.sh uninstall 82
cd /www/server/mdserver-web/plugins/php/versions/82 && bash sg11.sh uninstall 82
```

## 错误截图 ?

![image](https://user-images.githubusercontent.com/43872911/211745360-eaa55826-d430-4a43-8fa8-38e6ccde5fe9.png)

## 浏览器版本 ?

Microsoft Edge
版本 108.0.1462.76 (正式版本) (64 位)

## 软件版本(插件/面板) ?

php8.2 dev面板

**Comment by midoks** [comment]
嗯，等等，说不定后续就支持了，我暂时不改了。
