### ISSUE TITLE
Webhook 插件存在多处BUG

### ISSUE THREAD

**Issue by garryde** [midoks/mdserver-web#338]
## 什么系统 ?

Ubuntu 22.04.1 LTS ARM

## 错误信息 ?

1: Webhook插件无法传递参数到$1，参数识别 为空
2:通过POST方法调用插件的调用地址（http://IP:24707/hook?access_key）会被面板拦截，出现入口不正确的提示。

**Comment by midoks** [comment]
已经优化。
