### ISSUE TITLE
www/server/php/app_start.php) is not within the allowed path(s)

### ISSUE THREAD

**Issue by digdigdog** [midoks/mdserver-web#34]
搭建发卡系统，搭建完成后访问首页提示这个错误

Warning: Unknown: open_basedir restriction in effect. File(/www/server/php/app_start.php) is not within the allowed path(s): (/www/wwwroot/xxx.cc/public/:/tmp/:/proc/) in Unknown on line 0

Warning: Unknown: failed to open stream: Operation not permitted in Unknown on line 0

Fatal error: Unknown: Failed opening required '/www/server/php/app_start.php' (include_path='.:/www/server/php/73/lib/php') in Unknown on line 0

**Comment by midoks** [comment]
已经修复

**Comment by harry3633** [comment]
感觉问题还在，搭建 https://github.com/pereorga/minimalist-web-notepad ，之前我用宝塔搭建，刚刚转过来出现的，不知道改哪里。
Warning: Unknown: open_basedir restriction in effect. File(/www/server/php/app_start.php) is not within the allowed path(s): (/www/wwwroot/note.mianao.info/:/tmp/) in Unknown on line 0

Warning: Unknown: failed to open stream: Operation not permitted in Unknown on line 0

Fatal error: Unknown: Failed opening required '/www/server/php/app_start.php' (include_path='.:') in Unknown on line 0
