### ISSUE TITLE
不支持macos,希望支持😂

### ISSUE THREAD

**Issue by 1099438829** [midoks/mdserver-web#344]
## 什么系统 ?

macos 

## 错误信息 ?

bash: line 109: cd: /www/server/mdserver-web: No such file or directory
bash: line 111: cd: /www/server/mdserver-web: No such file or directory
.....................start mw fail
## 错误截图 ?

<img width="585" alt="image" src="https://user-images.githubusercontent.com/2869110/213118270-fb0ce469-5528-4c92-90ba-bd7980410dda.png">

## 软件版本(插件/面板) ?

...

**Comment by midoks** [comment]
mac是dev环境，等我以后调整一下吧，现阶段暂时没空。
你把代码搞下来，执行如下:
pip install -r requirements.txt 
./cli.sh debug
即可。可能会出问题，自己研究一下了。

**Comment by 1099438829** [comment]
虽然我会写python 但是作为伸手党你出的东西我都是 默默的加载 提问题 等你修复然后继续用哈哈哈哈 docker 也起不来我默默的mdserver软件继续

**Comment by midoks** [comment]
> 虽然我会写python 但是作为伸手党你出的东西我都是 默默的加载 提问题 等你修复然后继续用哈哈哈哈 docker 也起不来我默默的mdserver软件继续

那你等一下咯。我3月后，优化一下。

**Comment by 1099438829** [comment]
好嘞 点个赞

**Comment by midoks** [comment]
curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/midoks/mdserver-web/dev/scripts/install_dev.sh | bash

已经进行微调，仅限于开发测试。
