### ISSUE TITLE
debian11 同时检测到iptables 和 firewalld，修改防火墙后不生效

### ISSUE THREAD

**Issue by feyanru** [midoks/mdserver-web#345]
## 什么系统 ?
Debian 11
## 错误信息 ?

/usr/sbin/ 里同时有iptables 和 firewalld  ，而iptables不可用，firewalld 也不执行，换端口后就无法访问

## 软件版本(插件/面板) ?
dev
...

**Comment by midoks** [comment]
已经优化了

**Comment by feyanru** [comment]
感谢，ok了
