### ISSUE TITLE
面板里的 安全  防火墙，无作用，不管是放行还是禁用，都不受控制

### ISSUE THREAD

**Issue by gaoyuoppa** [midoks/mdserver-web#347]
## 什么系统 ?

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

## 错误信息 ?
面板里的 安全  防火墙，无作用，不管是放行还是禁用，都不受控制

服务商提供的一键安装系统，重装过，目前还是一样问题。

Ex:
```bash
一个issue，一个问题。多余问题，视情况而答。
```

## 错误截图 ?

![QQ截图20230124142830](https://user-images.githubusercontent.com/20106653/214227466-6e29a98b-ba48-4d73-92a7-63501e5ae5a0.png)
![QQ截图20230124143501](https://user-images.githubusercontent.com/20106653/214227469-46b0c19f-43bd-46e6-ae51-408c07b461ac.png)
![QQ截图20230124143613](https://user-images.githubusercontent.com/20106653/214227472-14e44c77-c95d-4df5-a0a9-f54591f808c4.png)
![QQ截图20230124143831](https://user-images.githubusercontent.com/20106653/214227474-5e836eec-e435-43e8-8fc8-317e5b6cde29.png)

...

## 浏览器版本 ?
Chrome 95
...

## 软件版本(插件/面板) ?
0.12.1
...

**Comment by midoks** [comment]
是这样的，这个bug，修改了。但是，还在新开发东西，还未合并。mw update_dev。更新到最新版，即可正常使用。

**Comment by cgisky1980** [comment]
> mw update_dev

试了更新到最dev新版 还是没起作用

**Comment by 36h** [comment]
我的也是这样可能是bug OP防火墙 0.2.3 面板版本0.12.2.1  在Debian 11中已经安装了，启动不了，点击卸载没有反应，重载配置也不能启动了
