### ISSUE TITLE
建议请求,软件管理 添加 已安装。

### ISSUE THREAD

**Issue by leeaikong** [midoks/mdserver-web#351]
## 需求

建议请求,软件管理 添加 已安装 标签。

在选定已安装标签时， 打开软件管理 默认显示已安装的软件列表  （跟宝塔一样）

有些已安装的软件 需要进入设置 或者重启   要一个个去找 有点太麻烦了

希望采纳

## 提供参考

给开发者提供参考！

**Comment by midoks** [comment]
已加，重新需求。
