### ISSUE TITLE
phpmyadmin打开地址错误

### ISSUE THREAD

**Issue by leeaikong** [midoks/mdserver-web#353]
版本 0.12.2    虚拟机安装centos7.9

1 安装成功后  显示的 只有一个地址 是外网IP管理面板地址    （希望新增内网IP的面板地址）

2 安装phpmyadmin 后 在 mysql的管理列表中 点击 phpmyadmin的链接  打开的也是外网的IP地址    （这里也应该改一下 ）

3，phpmyadmin里的 主页标签   里面的链接也是同样

由于我是虚拟机里测试 根本打不开外网ip的地址 

酌情修改吧   不是什么大问题

# 面板设置 ，  服务器IP 地址，  修改为内网IP  就好了。

**Comment by midoks** [comment]
默认外网。
