### ISSUE TITLE
0.12.2版本op-waf 0.2.4 导致CPU过高

### ISSUE THREAD

**Issue by tomlei88** [midoks/mdserver-web#358]
## 什么系统 ?

CentOS Linux 7.8.2003 (Core)　

## 错误信息 ?

Ex:
0.12.2版本op-waf 0.2.4 导致CPU过高，卸载后恢复正常。

## 错误截图 ?

![image](https://user-images.githubusercontent.com/103014450/216061281-df6d838a-6416-494f-abc6-ba605951b60b.png)

![image](https://user-images.githubusercontent.com/103014450/216061335-b931321e-9704-48d7-8e67-b52b9342fb90.png)

![image](https://user-images.githubusercontent.com/103014450/216061380-6fb1dbb5-060b-4f90-8a4a-1755b6cc00bc.png)

## 软件版本(插件/面板) ?

0.12.2版本op-waf 0.2.4

**Comment by tomlei88** [comment]
> 查过日志没，到底是什么原因？

大佬具体查哪个日志，我记得waf点重载配置会报错，闪的太快没截图，卸载也卸载不掉，要先把openresty卸载才能卸载掉waf，然后重装openresty.
两台服务器都是会cpu过高。目前卸载waf观察一天没在出现了。

**Comment by tomlei88** [comment]
1

**Comment by midoks** [comment]
你怎么关了呀，原因都没有查到。

**Comment by tomlei88** [comment]
> 你怎么关了呀，原因都没有查到。
重新复现了下，这是op-waf 点击重载配置 的报错
![360截图20230202163423721](https://user-images.githubusercontent.com/103014450/216273314-07276f8e-b381-47c2-8c1e-cda0ce63d191.jpg)

**Comment by tomlei88** [comment]
> > 你怎么关了呀，原因都没有查到。
> > 重新复现了下，这是op-waf 点击重载配置 的报错
> > ![360截图20230202163423721](https://user-images.githubusercontent.com/103014450/216273314-07276f8e-b381-47c2-8c1e-cda0ce63d191.jpg)

![cpu](https://user-images.githubusercontent.com/103014450/216275486-a3f19100-86ab-4b26-83f3-946a4fc85a26.jpg)

**Comment by tomlei88** [comment]
> 你怎么关了呀，原因都没有查到。

之前更新，没有按照如下操作:
https://github.com/midoks/mdserver-web/pull/328

处理后，mw update_dev

-----------------------------------------------------------

大佬你好，按照上面的步骤操作，点击重载waf 确实不报错了。但到晚上访问高峰的时候 Cpu 又经常过高，偶尔100% 。对比下来确实高了不少，卸载waf后CPU立刻下来了。
用两台服务器做对比一台访问量大，未安装waf 的CPU利用率反而低，另一台安装了waf [cpu利用率高了30%以上。
这种应该怎么排查呢？



![ssss](https://user-images.githubusercontent.com/103014450/216350186-2b5b5c7d-b99f-4387-a920-dee9d5b776c3.jpg)
![b](https://user-images.githubusercontent.com/103014450/216350219-5576e688-688d-436a-ad86-f94a1a92895f.png)
![h](https://user-images.githubusercontent.com/103014450/216350246-40ee0d4e-0f05-47bb-bce3-901822d4f501.jpg)

**Comment by midoks** [comment]
你好，非常感谢你详细的信息。但是由于我并没有大流量的网站，所以，我自己排查不了。如果，你能提供你网站，我来排查，并优化最好了，我才能知道问题在哪里。如果方便，可以通过TG联系到我。如果不方便，就算了。等待我那一天，我有大流量网站，才能优化了。

**Comment by tomlei88** [comment]
> 你好，非常感谢你详细的信息。但是由于我并没有大流量的网站，所以，我自己排查不了。如果，你能提供你网站，我来排查，并优化最好了，我才能知道问题在哪里。如果方便，可以通过TG联系到我。如果不方便，就算了。等待我那一天，我有大流量网站，才能优化了。

感谢你的回复，无偿使用的面板已经很优秀了。 请问怎么联系你呢

**Comment by midoks** [comment]
> > 你好，非常感谢你详细的信息。但是由于我并没有大流量的网站，所以，我自己排查不了。如果，你能提供你网站，我来排查，并优化最好了，我才能知道问题在哪里。如果方便，可以通过TG联系到我。如果不方便，就算了。等待我那一天，我有大流量网站，才能优化了。
> 
> 感谢你的回复，无偿使用的面板已经很优秀了。 请问怎么联系你呢

![image](https://user-images.githubusercontent.com/4169529/216363668-06e0454b-ba58-4838-921d-41925f6064c8.png)
首页就有。

**Comment by tomlei88** [comment]
添加不上 ![Screenshot_2023-02-02-23-17-10-261_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/103014450/216364477-ce936a86-3e27-4d74-81fb-00582cde6d85.jpg)

**Comment by midoks** [comment]
你为什么不回答呢？ 你TG的名字是那个？

**Comment by tomlei88** [comment]
> 你为什么不回答呢？ 你TG的名字是那个？
tom3958
