### ISSUE TITLE
反向代理视乎存在问题。

### ISSUE THREAD

**Issue by gaoyuoppa** [midoks/mdserver-web#359]
## 什么系统 ?

Debian 11,,Ubuntu 20 均测试过

## 错误信息 ?
反代 https://www.runpod.cn/docs/5/37.html  这个论坛程序
BT可以，但是mdserver-web，反代以后，大部分正常注册，还有一部分提示验证码错误，
联系runpod这个程序的作者，答曰：
【mb面板装的nginx用不了$connection_upgrade变量】

## 错误截图 ?

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?
0.12.2

**Comment by cyril-cheng** [comment]
既然这样，你把BT的反代代码搬过来不就行了。
nginx的默认代理是http1.0，有些网站反代以后会出现js，css，图片等静态资源加载异常。
在反代配置里开启http1.1就行了。
proxy_http_version 1.1;  #开启对http1.1支持
proxy_set_header Connection "";  #设置Connection为空串,以禁止传递头部到后端

**Comment by gaoyuoppa** [comment]
> 

好的
