### ISSUE TITLE
网站统计ip统计和URI统计空白

### ISSUE THREAD

**Issue by tomlei88** [midoks/mdserver-web#360]
## 什么系统 ?

centos 7.8

## 错误信息 ?

网站统计ip统计和URI统计和 T日正常，T+1日发现无数据，点击openresty 重载后有数据出现。

## 错误截图 ?
今日空白
![今日空白2](https://user-images.githubusercontent.com/103014450/216532210-e404342c-b6bc-4974-aed3-c7cfe41fe7a2.png)

![今日空白](https://user-images.githubusercontent.com/103014450/216532223-2e10b741-899e-4d77-b619-170dfffe04ac.png)
昨日正常
![昨天正常](https://user-images.githubusercontent.com/103014450/216532244-9b903eb6-fb38-49fb-8238-0d27e47aff38.png)

openresty 重载后you数据
![重启后1](https://user-images.githubusercontent.com/103014450/216533092-b32c5b5c-5264-4996-aa89-d416b14c9e69.png)

![重启后2](https://user-images.githubusercontent.com/103014450/216532322-0dea6c9b-58ec-42c6-b13c-fbe2a749a7d0.png)

openresty 重载后有数据出现

## 软件版本(插件/面板) ?

系统:CentOS Linux 7.8.2003 (Core)　　0.12.2 版本 openresty 1.17.8.2 网站统计 0.2.3 
...

**Comment by midoks** [comment]
已经解决
