### ISSUE TITLE
debain 11 安装  mysql 8.0 和 mongodb 5.x 版本失败

### ISSUE THREAD

**Issue by gclm** [midoks/mdserver-web#367]
## 什么系统 ?

- Debian GNU/Linux 11 (bullseye)　

## 错误信息 ?
任务列表上显示mysql 和 mongodb 安装成功，但是软件列表已安装里面没有

## 错误截图 ?
<img width="795" alt="image" src="https://user-images.githubusercontent.com/27618687/218307146-e78a855b-2d94-4d05-82cf-c4827493d947.png">
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/27618687/218307228-18e4571c-3962-4ebb-9571-f739447f2770.png">
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/27618687/218307239-ced0fc0b-7241-477f-947d-b651aad73aa9.png">

## 浏览器版本 ?
 - Google Chrome | 108.0.5359.124 (正式版本) (x86_64)

## 软件版本(插件/面板) ?
- 面板版本：0.12.2
...

**Comment by midoks** [comment]
分开提供一下，mysql8.0和mongodb 执行日志

**Comment by gclm** [comment]
切换操作系统了，现在换成centos7 一起正常，另外执行日志在哪里啊
