### ISSUE TITLE
acme.sh 证书路径

### ISSUE THREAD

**Issue by Wittoy** [midoks/mdserver-web#374]
## 什么系统 ?

Debian 11

## 错误信息 ?

acme.sh默认证书已由rsa证书变换为ecc证书，其证书路径名 `<domain>_ecc`
https://github.com/acmesh-official/acme.sh/commit/ec0e871592d286b8cd4e1d407411f0ba17c775e6
导致安装证书时读取不了正确路径，返回签发失败消息

## 软件版本(插件/面板) ?

0.12.3

**Comment by midoks** [comment]
已经修复
