### ISSUE TITLE
OpenResty 无法修改配置

### ISSUE THREAD

**Issue by illuz** [midoks/mdserver-web#376]
## 什么系统 ?

Debian 11

## BUG 描述

OpenResty 在插件面板上修改过配置后，如果把重启 OpenResty，会把配置重置。

具体原因是这次提交 https://github.com/midoks/mdserver-web/commit/4e6a54dbad74ef4d1ab5cb1c3497367f177664f5

之前是在第一次初始化目录的情况下才会去初始化配置文件，新的逻辑好像是为了让大版本升级也能自动更新配置文件，所以在所有启动的情况下都去更新配置文件，导致配置的重置。

## 建议

将代码逻辑回滚，将「大版本升级自动添加新的 Lua 配置文件」写在 update.sh 里面。

**Comment by midoks** [comment]
建议无效，自有安排。
