### ISSUE TITLE
增加已删除过的域名会提示站点已存在

### ISSUE THREAD

**Issue by shaozi17** [midoks/mdserver-web#377]
## 什么系统 ?

Centos7.5

## 错误信息 ?

从外部添加的域名删除之后,在站点修改里面重新添加会提示站点已存在/已绑定
Ex:
```bash
一个issue，一个问题。多余问题，视情况而答。
```

## 错误截图 ?
![image](https://user-images.githubusercontent.com/22265868/220575742-b8e28f64-036e-48fb-983f-a9dd98b91308.png)
![image](https://user-images.githubusercontent.com/22265868/220575992-00b3848d-d113-4648-8ed0-42fd24fbd4de.png)

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?
0.12.3
...

**Comment by midoks** [comment]
已经修复，等待合并。
