### ISSUE TITLE
证书申请BUG

### ISSUE THREAD

**Issue by shaozi17** [midoks/mdserver-web#378]
## 什么系统 ?

Centos7.5

## 错误信息 ?
同时勾选两个域名申请证书的时候
有时候会出现/www/server/web_conf/letsencrypt目录保存的证书域名目录与/www/server/web_conf/ssl中的软连接域名目录不对应的情况

## 错误截图 ?
![image](https://user-images.githubusercontent.com/22265868/220576432-7f4bc9fc-cde5-4e24-bb3b-edbc761e9d69.png)
![image](https://user-images.githubusercontent.com/22265868/220576849-21e07bd3-6b9c-459c-8690-e4ed3f5a4d58.png)

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

...

**Comment by midoks** [comment]
仅和主配置域名关联，请设置正确的域名。

**Comment by midoks** [comment]
![image](https://user-images.githubusercontent.com/4169529/221006597-c11c9b4b-d662-43fa-94cc-3dc5c52a3b2d.png)
有效。

**Comment by shaozi17** [comment]
你测试的时候有效可能是因为你添加的主域名是dev38.xxx.com 辅域名是dev383.xxx.com,
我猜测是主域名名字的ascii码排序比辅域名低的时候才会出现这种情况,
例如主域名为api.xx.com 辅域名为apiadmin.xx.com
这种情况就会复现bug了
