### ISSUE TITLE
请问FTP和数据库管理的菜单可以做到左侧导航上吗

### ISSUE THREAD

**Issue by bg7758** [midoks/mdserver-web#379]
用习惯了宝塔的数据库管理，不知道作者不在导航上放入口是否有别的深意
需要调试数据库的时候 必须要先点开插件，再打开数据库的设置，再点击管理，路径加长了
且在窗口里面操作感觉有点别扭  菜单一长 自动换行 操作不太方便

**Comment by midoks** [comment]
请自己重构。
