### ISSUE TITLE
域名绑定问题。

### ISSUE THREAD

**Issue by a55431** [midoks/mdserver-web#380]
## 什么系统 ?
Centos7.6

## 错误信息 ?
在新建网站后。绑定域名，如果绑定的域名列表仅为1个的时候，在删除网站后，此域名不可再用，提示XXX域名已被绑定

## 错误截图 ?
![1677127120558](https://user-images.githubusercontent.com/116335044/220822677-764e5951-98c3-405b-b623-7390cc9c7639.png)

ceshi1.com 是我新建网站后直接删除，然后此域名在网站ceshi.com里无法绑定，如果域名列表剩余大于1，则都可用。

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

...

**Comment by a55431** [comment]
现在可以通过，新建网站时，写入禁止绑定的域名，然后添加任意域名，再删除禁止绑定的域名，就可以正常绑定了。

**Comment by midoks** [comment]
OK，已在删除时。补上遗留的数据。
