### ISSUE TITLE
新添加的网站在网站统计插件和防火墙插件中看不到

### ISSUE THREAD

**Issue by ilay1678** [midoks/mdserver-web#381]
## 什么系统 ?

Debian 11

## 错误信息 ?

新添加的网站在网站统计插件和防火墙插件中看不到，手动重载网站统计插件后能看到了，但是统计不到数据

**Comment by midoks** [comment]
正常。 现在只能通过同步和重载。统计不到，是因为重构了。openresty需在卸载重载，才能正常使用。
