### ISSUE TITLE
定时任务在修改时区之后不会同步更改

### ISSUE THREAD

**Issue by 0honus0** [midoks/mdserver-web#385]
## 什么系统 ?

Debian 11?

## 错误信息 ?

开始添加的定时任务在修改时区之后仍然按照原来的时区时间运行，需要重启面板才可以生效

## 错误截图 ?

...

## 浏览器版本 ?

...

## 软件版本(插件/面板) ?

...

**Comment by midoks** [comment]
我认为是正常的。如果你有什么好办法，请告我。

**Comment by 0honus0** [comment]
看选项中有同步时间这一项，可以在同步完成之后重启定时任务task保证定时任务用的时间与面板显示时间一致
