### ISSUE TITLE
OP防火墙 0.2.3无法卸载？

### ISSUE THREAD

**Issue by harry3633** [midoks/mdserver-web#386]
## 什么系统 ?
Debian 11 x64 (bullseye)

## 错误信息 ?

想卸载防火墙
先关闭，点卸载，显示卸载成功，刷新后防火墙还在。
重启面板或系统，再点卸载，还是显示卸载成功，但防火墙一直都在

请问防火墙是无法卸载的吗？还是得用命令卸载？

...

**Comment by midoks** [comment]
下次合并，关闭issue。相关问题，请在bbs.midoks.me咨询。
