### ISSUE TITLE
重启服务器后，已经设定了自启动的无法自启动。

### ISSUE THREAD

**Issue by zhe1253** [midoks/mdserver-web#39]
重启服务器后，已经设定了自启动的openresty + mysql +php无法自启动。
手动点击启动后，MYSQL 无法启动，只能SSH连接服务器，使用 systemctl start mysql
才能启动MYSQL。

PHP53安装过程的出错了以后，想重复安装，无法正常重新安装，
只能手动删除  /www/server/php/53  and  /www/server/source/php/php53 相关目录，才能重新安装。

**Comment by midoks** [comment]
什么系统

**Comment by zhe1253** [comment]
debain 11

**Comment by midoks** [comment]
我也没有安装成功呀!,现在还没有时间专门处理。等等...

**Comment by midoks** [comment]
基本解决。PHP5.2 ,会尽量解决，但我劝你放弃。
