### ISSUE TITLE
在ubuntu上用了几天，一共发现几个bug，1免登陆问题，2，文件管理器，3数据库怎么都开不起来

### ISSUE THREAD

**Issue by cjx2000** [midoks/mdserver-web#42]
1，免登陆问题，换了几个浏览器，几个设备，几个ip，都可以免登陆，只要第一个登陆以后（这个bug致命性的）
2，文件管理器，复制，移动文件报错，试了几台vps都报错，错误内容（访问异常:decoding str is not supported!）
3，数据库怎么都开不起来，所有版本都重试了，之前的卸载干净了。
4，绑定域名和入口功能无效。
非常喜欢这个面板，简单高效，奈何水平不够，试了很久这些问题都不能解决。
希望大佬能修复一下，那就只用这个了 ：）

**Comment by cjx2000** [comment]
系统环境，ubuntu 18 
btw，感谢开发。

**Comment by midoks** [comment]
看了，脑瓜疼。
1.mysql我试了很多次。没有问题。
2.绑定域名不可能问题吧。

最新修了一些bug。
系统重现安装。再来测试一下看看。

**Comment by cjx2000** [comment]
1, 免登陆问题目前仅限于chrome通用户隐私模式还是免登陆，其它无问题了。
2，文件管理器问题依旧，复制文本文件会出现几个问题，一个是刚才的访问异常，二是复制文本例如1.txt复制过去文件名就剩下txt，重命名也是访问异常。目前问题比较突出的是多文件复制，重命名，复制文本文件（txt，php之类）可否告知官方文件是哪个，直接用官方的替换是否可行？

**Comment by cjx2000** [comment]
绑定域名问题，域名绑定保存后，刷新一下还是没有域名（上次也是这样），这次端口都改不了了。现在还在配置环境，待会儿重启试试。

**Comment by cjx2000** [comment]
> 看了，脑瓜疼。 1.mysql我试了很多次。没有问题。 2.绑定域名不可能问题吧。
> 
> 最新修了一些bug。 系统重现安装。再来测试一下看看。

新系统服务器试了，目前暂时发现的问题是
1，文件管理器问题依旧，复制文本文件会出现几个问题，一个是刚才的访问异常，二是复制文本例如1.txt复制过去文件名就剩下txt，重命名也是访问异常。目前问题比较突出的是多文件复制，重命名，复制文本文件（txt，php之类）
2，绑定域名问题，域名绑定保存后，刷新一下还是没有域名（上次也是这样）
3，申请ssl一直都这样（正在校验域名，请稍后...）很久很久后会报错，域名校验失败。
