### ISSUE TITLE
会支持openLitespeed/Litespeed吗？

### ISSUE THREAD

**Issue by franklight** [midoks/mdserver-web#43]

**Comment by midoks** [comment]
是PHP扩展? 加一个扩展简单。等等..

**Comment by pxw2002** [comment]
[openLitespeed
应该是n](https://www.ldhost.cn/jc/security/5863.html)   和nginx一样的

**Comment by franklight** [comment]
> 是PHP扩展? 加一个扩展简单。等等..

不是，是这个 https://openlitespeed.org/  类似于Nginx

**Comment by midoks** [comment]
已经搞了一下。
只是通过二进制安装了一下。
- https://github.com/mw-plugin/openlitespeed

![image](https://user-images.githubusercontent.com/4169529/175805328-277ad344-668c-4983-a038-49cc0b9d3732.png)


快速安装
```
curl -fsSL https://raw.githubusercontent.com/mw-plugin/openlitespeed/main/scripts/install.sh | bash
```
