### ISSUE TITLE
支持Python管理器

### ISSUE THREAD

**Issue by luckysdream** [midoks/mdserver-web#44]
请问后续是否有计划出Python管理器这种插件吗？

**Comment by midoks** [comment]
才写完。
![image](https://user-images.githubusercontent.com/4169529/174245852-0e5aeb91-eeb5-40a6-a2bf-ea3ee875f2c8.png)

**Comment by luckysdream** [comment]
> 才写完。 ![image](https://user-images.githubusercontent.com/4169529/174245852-0e5aeb91-eeb5-40a6-a2bf-ea3ee875f2c8.png) #31

更加具体来说的是具备对Python版本管理&包管理的那个Python管理器，因为绝大部分的项目都存在一定的版本要求和包要求。就想知道一下有没有这种功能的一个计划

**Comment by midoks** [comment]
pip3 install -r /www/server/mdserver-web/requirements.txt
or
python3 -m venv .

举个荔枝。
- https://blog.csdn.net/weixin_43224412/article/details/121731801
这种话，我比较困难。

**Comment by luckysdream** [comment]
> pip3 install -r /www/server/mdserver-web/requirements.txt or python3 -m venv .
> 
> 举个荔枝。
> 
> * https://blog.csdn.net/weixin_43224412/article/details/121731801
>   这种话，我比较困难。

了解了，我还是手动去部署吧。感谢解答
