### ISSUE TITLE
Questions & Sugassions

### ISSUE THREAD

**Issue by foxpcteam** [midoks/mdserver-web#45]
Hi, Great Project!

After playing with the panel, I have some questions and suggestions.

First, I will suggest creating a Roadmap for Beta Version and to stable V1.0

**Now the question is what you plan to add and when?**

1\. Manage multi servers from one panel  
2\. Users / Teams and Roles - this will allow adding users to panel and allow them to manage server / plugins / websites (based on permissions)  
3\. Full API Support - this will allow making many automations + allow creating new admin panel and etc...  
4\. DNS Management - you can use something like **bind9** to make this work, or to use any other app.  
  
5\. Email Management - if server provider allow sending email from the server and don't close SMTP port, i think RoundCube app would be great to manage the Emails as Local App.   
But most of the server providers are blocking the SMTP port and that's why we need to use external SMTP provider. to to solve this problem globally, need to add option to create multi smtp  
this will allow to assign smtp to server and this way all emails will be send fine + it will allow to assign to each website smtp from where he can send emails 

6\. Simple Backup and Restore - as for now, there is only local backup for "site" without the one click restore option.  
also need to allow backup / restore the hole system. this will allow quick to move from one server to another.  
\* its very important to add external backup options like Amazon S3, Wasabi, Backblaze etc...  
\* its very important to add schedule backup (each day, once a week etc...).

7\. One click install app - like Wordpress(if wordpress also add wpcli), drupal etc...

8\. multi language support for the admin panel

9\. Http/2 and Http/3 and HSTS support.

10\. Brotli / Gzip compression

11\. 7G Firewall

12\. Composer

13\. phppgadmin - phpMyAdmin alternative (allow user to choose with waht he want to work)

14\. PostgreSQL support

15\. SFTP -  much secury than regulat FTP

**Sugassions to Improve:**  
1\. allow to change server Time Zone from server settings  
2\. allow to manage multi IP address  
3\. allow to assisn IP address to website  
4\. allow site redirect to www or without www  
5\. allow site cloning  
6\. add wildcard Letsencrypt support  
7\. automatically install at least 2-3 php versions (lasts)  
6\. Improve security login:  
\* Two-factor Authentication  
\* Verification code that will send by email or sms.

**Comment by weiyidu** [comment]
> Hi, Great Project!
> 
> After playing with the panel, I have some questions and suggestions.
> 
> First, I will suggest creating a Roadmap for Beta Version and to stable V1.0
> 
> **Now the question is what you plan to add and when?**
> 
> 1. Manage multi servers from one panel 2. Users / Teams and Roles - this will allow adding users to panel and allow them to manage server / plugins / websites (based on permissions) 3. Full API Support - this will allow making many automations + allow creating new admin panel and etc... 4. DNS Management - you can use something like **bind9** to make this work, or to use any other app.
> 
> 5. Email Management - if server provider allow sending email from the server and don't close SMTP port, i think RoundCube app would be great to manage the Emails as Local App.  But most of the server providers are blocking the SMTP port and that's why we need to use external SMTP provider. to to solve this problem globally, need to add option to create multi smtp this will allow to assign smtp to server and this way all emails will be send fine + it will allow to assign to each website smtp from where he can send emails 
> 
> 6. Simple Backup and Restore - as for now, there is only local backup for "site" without the one click restore option. also need to allow backup / restore the hole system. this will allow quick to move from one server to another. * its very important to add external backup options like Amazon S3, Wasabi, Backblaze etc... * its very important to add schedule backup (each day, once a week etc...).
> 
> 7. One click install app - like Wordpress(if wordpress also add wpcli), drupal etc...
> 
> 8. multi language support for the admin panel
> 
> 9. Http/2 and Http/3 and HSTS support.
> 
> 10. Brotli / Gzip compression
> 
> 11. 7G Firewall
> 
> 12. Composer
> 
> 13. phppgadmin - phpMyAdmin alternative (allow user to choose with waht he want to work)
> 
> 14. PostgreSQL support
> 
> 15. SFTP -  much secury than regulat FTP
> 
> **Sugassions to Improve:** 1. allow to change server Time Zone from server settings 2. allow to manage multi IP address 3. allow to assisn IP address to website 4. allow site redirect to www or without www 5. allow site cloning 6. add wildcard Letsencrypt support 7. automatically install at least 2-3 php versions (lasts) 6. Improve security login: * Two-factor Authentication * Verification code that will send by email or sms.

you need  https://www.bt.cn/new/download.html

**Comment by foxpcteam** [comment]
> [weiyidu](/weiyidu)

The problem with BT and aaPanel is that they not really open source.

And of curse lost of security issues.

But thanks for the suggestion.

**Comment by weiyidu** [comment]
@foxpcteam 
mdserver-web 需要更多的开发者一起维护

**Comment by midoks** [comment]
First, need a new set of Web UI.
I use the BT Web UI. Otherwise, there is a problem.
I'm sure you're welcome to submit the code.

**Comment by foxpcteam** [comment]
> @foxpcteam mdserver-web needs more developers to maintain together

You are right. If the core was with full and strong API it could help.  
Also need to work on documentation, so other devs can help...  
i can help with PHP and JS

**Comment by foxpcteam** [comment]
> First, need a new set of Web UI. I use the BT Web UI. Otherwise, there is a problem. I'm sure you're welcome to submit the code.

You are right. If the core was with full and strong API it could help.  
Also need to work on documentation, so other devs can help...  
i can help with PHP and JS

**Comment by falcolee** [comment]
建议 Roadmap 放在readme里面，可以更多人看到一起开发一起助力。
You are right . A clear roadmap required.
