### ISSUE TITLE
【debian】消息盒子与后台不同步显示

### ISSUE THREAD

**Issue by uselibrary** [midoks/mdserver-web#50]
Debian 11，纯净安装。在应用商店中点击安装后，后台通过htop可以查看正在编译，但前台消息盒子不显示。可能还存在队列问题，即一次性点击多个软件进行安装，后面的几个软件可能并不会被安装。
![msg_bug](https://user-images.githubusercontent.com/34091189/174295675-b8ab33da-b295-4fcf-8d63-514b9e18bd59.jpg)

**Comment by midoks** [comment]
你是不是在安装的过程中，重启的面板，执行 service mw restart  |  system mw restart 命令。

**Comment by midoks** [comment]
我增强任务的功能。但是不知道什么导致了你这个原因。你最好把`执行日志`，发出来。不然我无法判断。

**Comment by midoks** [comment]
已经复现并解决了。
