### ISSUE TITLE
debain 11  安装 php 5.3 失败

### ISSUE THREAD

**Issue by zhe1253** [midoks/mdserver-web#53]
全新安装debain 11 ，安装mdserver-web 后，直接安装   php 5.3
直接失败，日志：
`
2022-06-17 09:35:31 (3.47 MB/s) - ‘/www/server/source/php/php-5.3.29.tar.xz’ saved [9142540/9142540]

+ cd /www/server/source/php
+ tar -Jxf /www/server/source/php/php-5.3.29.tar.xz
+ mv /www/server/source/php/php-5.3.29 /www/server/source/php/php53
+ '[' -f /www/server/php/53/bin/php.dSYM ']'
+ '[' -f /www/server/php/53/sbin/php-fpm.dSYM ']'
+ '[' -f /www/server/php/53/bin/php ']'
+ OPTIONS=
+ '[' Linux == Darwin ']'
+ OPTIONS=--with-iconv=/www/server/lib/libiconv
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old --with-gd --enable-gd-native-ttf'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old --with-gd --enable-gd-native-ttf --with-curl'
+ '[' '!' -d /www/server/php/53 ']'
+ '[' -f /www/server/php/53/bin/php.dSYM ']'
+ '[' -f /www/server/php/53/sbin/php-fpm.dSYM ']'
+ '[' '!' -d /www/server/php/53/lib/php/extensions/no-debug-non-zts-20090626 ']'

然后第二次再安装 ，还是没有成功安装，最后日志是：
`zlib-1.2.11/win32/zlib.def
zlib-1.2.11/win32/zlib1.rc
zlib-1.2.11/zconf.h
zlib-1.2.11/zconf.h.cmakein
zlib-1.2.11/zconf.h.in
zlib-1.2.11/zlib.3
zlib-1.2.11/zlib.3.pdf
zlib-1.2.11/zlib.h
zlib-1.2.11/zlib.map
zlib-1.2.11/zlib.pc.cmakein
zlib-1.2.11/zlib.pc.in
zlib-1.2.11/zlib2ansi
zlib-1.2.11/zutil.c
zlib-1.2.11/zutil.h
Checking for gcc...
Checking for shared library support...
Building shared library libz.so.1.2.11 with gcc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o adler32.o adler32.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o crc32.o crc32.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o deflate.o deflate.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o infback.o infback.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inffast.o inffast.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inflate.o inflate.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inftrees.o inftrees.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o trees.o trees.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o zutil.o zutil.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o compress.o compress.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o uncompr.o uncompr.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzclose.o gzclose.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzlib.o gzlib.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzread.o gzread.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example example.o -L. libz.a
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o minigzip.o test/minigzip.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip minigzip.o -L. libz.a
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/adler32.o adler32.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/crc32.o crc32.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/deflate.o deflate.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/infback.o infback.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inffast.o inffast.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inflate.o inflate.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/inftrees.o inftrees.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/trees.o trees.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/zutil.o zutil.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/compress.o compress.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/uncompr.o uncompr.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzclose.o gzclose.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzlib.o gzlib.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzread.o gzread.c
gcc -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzwrite.o gzwrite.c
gcc -shared -Wl,-soname,libz.so.1,--version-script,zlib.map -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o libz.so.1.2.11 adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo zutil.lo compress.lo uncompr.lo gzclose.lo gzlib.lo gzread.lo gzwrite.lo  -lc
rm -f libz.so libz.so.1
ln -s libz.so.1.2.11 libz.so
ln -s libz.so.1.2.11 libz.so.1
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o examplesh example.o -L. libz.so.1.2.11
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzipsh minigzip.o -L. libz.so.1.2.11
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o example64.o test/example.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o example64 example64.o -L. libz.a
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -D_FILE_OFFSET_BITS=64 -c -o minigzip64.o test/minigzip.c
gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o minigzip64 minigzip64.o -L. libz.a
rm -f /www/server/lib/zlib/lib/libz.a
cp libz.a /www/server/lib/zlib/lib
chmod 644 /www/server/lib/zlib/lib/libz.a
cp libz.so.1.2.11 /www/server/lib/zlib/lib
chmod 755 /www/server/lib/zlib/lib/libz.so.1.2.11
rm -f /www/server/lib/zlib/share/man/man3/zlib.3
cp zlib.3 /www/server/lib/zlib/share/man/man3
chmod 644 /www/server/lib/zlib/share/man/man3/zlib.3
rm -f /www/server/lib/zlib/lib/pkgconfig/zlib.pc
cp zlib.pc /www/server/lib/zlib/lib/pkgconfig
chmod 644 /www/server/lib/zlib/lib/pkgconfig/zlib.pc
rm -f /www/server/lib/zlib/include/zlib.h /www/server/lib/zlib/include/zconf.h
cp zlib.h zconf.h /www/server/lib/zlib/include
chmod 644 /www/server/lib/zlib/include/zlib.h /www/server/lib/zlib/include/zconf.h
+ '[' '!' -d /www/server/source/php/php53 ']'
+ '[' -f /www/server/php/53/bin/php.dSYM ']'
+ '[' -f /www/server/php/53/sbin/php-fpm.dSYM ']'
+ '[' -f /www/server/php/53/bin/php ']'
+ OPTIONS=
+ '[' Linux == Darwin ']'
+ OPTIONS=--with-iconv=/www/server/lib/libiconv
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old --with-gd --enable-gd-native-ttf'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old --with-gd --enable-gd-native-ttf --with-curl'
+ '[' '!' -d /www/server/php/53 ']'
+ '[' -f /www/server/php/53/bin/php.dSYM ']'
+ '[' -f /www/server/php/53/sbin/php-fpm.dSYM ']'
+ '[' '!' -d /www/server/php/53/lib/php/extensions/no-debug-non-zts-20090626 ']'
`

然后想去安装 PHP 7.4 还是出错，日志：
`rm -f /www/server/lib/libzip/share/man/man3/zip_file_error_get.3
rm -f /www/server/lib/libzip/share/man/man3/zip_error_init_with_code.3
rm -f /www/server/lib/libzip/share/man/man3/zip_file_replace.3
rm -f /www/server/lib/libzip/share/man/man3/zip_file_extra_field_delete_by_id.3
rm -f /www/server/lib/libzip/share/man/man3/zip_file_extra_field_get_by_id.3
rm -f /www/server/lib/libzip/share/man/man3/zip_file_extra_fields_count_by_id.3
rm -f /www/server/lib/libzip/share/man/man3/zip_fopen_index.3
rm -f /www/server/lib/libzip/share/man/man3/zip_fopen_index_encrypted.3
rm -f /www/server/lib/libzip/share/man/man3/zip_replace.3
rm -f /www/server/lib/libzip/share/man/man3/zip_open_from_source.3
rm -f /www/server/lib/libzip/share/man/man3/zip_stat_index.3
rm -f /www/server/lib/libzip/share/man/man3/zip_source_function_create.3
rm -f /www/server/lib/libzip/share/man/man3/zip_strerror.3
rm -f /www/server/lib/libzip/share/man/man3/zip_source_win32a_create.3
rm -f /www/server/lib/libzip/share/man/man3/zip_source_win32handle_create.3
rm -f /www/server/lib/libzip/share/man/man3/zip_source_win32w_create.3
ln -f /www/server/lib/libzip/share/man/man3/zip_error_clear.3 /www/server/lib/libzip/share/man/man3/zip_file_error_clear.3
ln -f /www/server/lib/libzip/share/man/man3/zip_error_get.3 /www/server/lib/libzip/share/man/man3/zip_file_error_get.3
ln -f /www/server/lib/libzip/share/man/man3/zip_error_init.3 /www/server/lib/libzip/share/man/man3/zip_error_init_with_code.3
ln -f /www/server/lib/libzip/share/man/man3/zip_file_add.3 /www/server/lib/libzip/share/man/man3/zip_file_replace.3
ln -f /www/server/lib/libzip/share/man/man3/zip_file_extra_field_delete.3 /www/server/lib/libzip/share/man/man3/zip_file_extra_field_delete_by_id.3
ln -f /www/server/lib/libzip/share/man/man3/zip_file_extra_field_get.3 /www/server/lib/libzip/share/man/man3/zip_file_extra_field_get_by_id.3
ln -f /www/server/lib/libzip/share/man/man3/zip_file_extra_fields_count.3 /www/server/lib/libzip/share/man/man3/zip_file_extra_fields_count_by_id.3
ln -f /www/server/lib/libzip/share/man/man3/zip_fopen.3 /www/server/lib/libzip/share/man/man3/zip_fopen_index.3
ln -f /www/server/lib/libzip/share/man/man3/zip_fopen_encrypted.3 /www/server/lib/libzip/share/man/man3/zip_fopen_index_encrypted.3
ln -f /www/server/lib/libzip/share/man/man3/zip_add.3 /www/server/lib/libzip/share/man/man3/zip_replace.3
ln -f /www/server/lib/libzip/share/man/man3/zip_open.3 /www/server/lib/libzip/share/man/man3/zip_open_from_source.3
ln -f /www/server/lib/libzip/share/man/man3/zip_stat.3 /www/server/lib/libzip/share/man/man3/zip_stat_index.3
ln -f /www/server/lib/libzip/share/man/man3/zip_source_function.3 /www/server/lib/libzip/share/man/man3/zip_source_function_create.3
ln -f /www/server/lib/libzip/share/man/man3/zip_file_strerror.3 /www/server/lib/libzip/share/man/man3/zip_strerror.3
ln -f /www/server/lib/libzip/share/man/man3/zip_source_win32a.3 /www/server/lib/libzip/share/man/man3/zip_source_win32a_create.3
ln -f /www/server/lib/libzip/share/man/man3/zip_source_win32handle.3 /www/server/lib/libzip/share/man/man3/zip_source_win32handle_create.3
ln -f /www/server/lib/libzip/share/man/man3/zip_source_win32w.3 /www/server/lib/libzip/share/man/man3/zip_source_win32w_create.3
make[3]: Leaving directory '/www/server/source/lib/libzip-1.3.2/man'
make[2]: Leaving directory '/www/server/source/lib/libzip-1.3.2/man'
make[1]: Leaving directory '/www/server/source/lib/libzip-1.3.2/man'
Making install in src
make[1]: Entering directory '/www/server/source/lib/libzip-1.3.2/src'
make[2]: Entering directory '/www/server/source/lib/libzip-1.3.2/src'
/bin/mkdir -p '/www/server/lib/libzip/bin'
/bin/sh ../libtool   --mode=install /bin/install -c zipcmp zipmerge ziptool '/www/server/lib/libzip/bin'
libtool: install: /bin/install -c .libs/zipcmp /www/server/lib/libzip/bin/zipcmp
libtool: install: /bin/install -c .libs/zipmerge /www/server/lib/libzip/bin/zipmerge
libtool: install: /bin/install -c .libs/ziptool /www/server/lib/libzip/bin/ziptool
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/www/server/source/lib/libzip-1.3.2/src'
make[1]: Leaving directory '/www/server/source/lib/libzip-1.3.2/src'
Making install in regress
make[1]: Entering directory '/www/server/source/lib/libzip-1.3.2/regress'
make[2]: Entering directory '/www/server/source/lib/libzip-1.3.2/regress'
not installing shared objects needed only for testing
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/www/server/source/lib/libzip-1.3.2/regress'
make[1]: Leaving directory '/www/server/source/lib/libzip-1.3.2/regress'
Making install in examples
make[1]: Entering directory '/www/server/source/lib/libzip-1.3.2/examples'
make[2]: Entering directory '/www/server/source/lib/libzip-1.3.2/examples'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/www/server/source/lib/libzip-1.3.2/examples'
make[1]: Leaving directory '/www/server/source/lib/libzip-1.3.2/examples'
make[1]: Entering directory '/www/server/source/lib/libzip-1.3.2'
make[2]: Entering directory '/www/server/source/lib/libzip-1.3.2'
make[2]: Nothing to be done for 'install-exec-am'.
/bin/mkdir -p '/www/server/lib/libzip/lib/pkgconfig'
/bin/install -c -m 644 libzip.pc '/www/server/lib/libzip/lib/pkgconfig'
make[2]: Leaving directory '/www/server/source/lib/libzip-1.3.2'
make[1]: Leaving directory '/www/server/source/lib/libzip-1.3.2'
+ '[' '!' -d /www/server/source/php/php74 ']'
+ cd /www/server/source/php/php74
+ OPTIONS=
+ '[' Linux == Darwin ']'
+ OPTIONS=--with-iconv=/www/server/lib/libiconv
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype --with-gd --enable-gd-native-ttf'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype --with-gd --enable-gd-native-ttf --with-curl'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype --with-gd --enable-gd-native-ttf --with-curl --with-libzip=/www/server/lib/libzip'
+ echo /www/server/source/php/php74
/www/server/source/php/php74
+ '[' '!' -d /www/server/php/74 ']'
+ cd /www/server/source/php/php74
+ ./buildconf --force
buildconf: Checking installation
buildconf: autoconf version 2.69 (ok)
buildconf: Forcing buildconf. The configure files will be regenerated.
buildconf: Cleaning cache and configure files
buildconf: Rebuilding configure
/usr/bin/m4:/tmp/am4t6l7ZX9/traces.m4:2966: ERROR: end of file in string
/usr/bin/m4:/tmp/am4t6l7ZX9/traces.m4:3019: ERROR: end of file in string
buildconf: Rebuilding main/php_config.h.in
autom4te: cannot rename autom4te.cache/traces.0t as autom4te.cache/traces.0: No such file or directory
buildconf: Rebuilding main/php_config.h.in
buildconf: Run ./configure to proceed with customizing the PHP build.
+ ./configure --prefix=/www/server/php/74 --exec-prefix=/www/server/php/74 --with-config-file-path=/www/server/php/74/etc --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --enable-mbstring --with-zlib-dir=/www/server/lib/zlib --enable-ftp --enable-sockets --enable-simplexml --enable-soap --enable-posix --enable-sysvmsg --enable-sysvsem --enable-sysvshm --disable-intl --disable-fileinfo --with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype --with-gd --enable-gd-native-ttf --with-curl --with-libzip=/www/server/lib/libzip --enable-fpm
+ make
make: *** No targets specified and no makefile found.  Stop.
buildconf: Run ./configure to proceed with customizing the PHP build.
+ ./configure --prefix=/www/server/php/74 --exec-prefix=/www/server/php/74 --with-config-file-path=/www/server/php/74/etc --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --enable-mbstring --with-zlib-dir=/www/server/lib/zlib --enable-ftp --enable-sockets --enable-simplexml --enable-soap --enable-posix --enable-sysvmsg --enable-sysvsem --enable-sysvshm --disable-intl --disable-fileinfo --with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype --with-gd --enable-gd-native-ttf --with-curl --with-libzip=/www/server/lib/libzip --enable-fpm
+ make
make: *** No targets specified and no makefile found.  Stop.`
`

**Comment by zhe1253** [comment]
最后是 先安装了MYSQL，然后再安装PHP7.4 成功了
不过php 5.3 怎么安都不行全是失败，而且显示0秒安装成功。

**Comment by midoks** [comment]
已修复
