### ISSUE TITLE
纯IPV6服务器安装后，不能访问后台，添加文件后只能重启

### ISSUE THREAD

**Issue by Audyna** [midoks/mdserver-web#56]
因为默认后台是没有监听IPV6的,造成无法登录，现在在/www/server/mdserver-web/data目录下添加ipv6.pl文件，然后重启服务器才能开启ipv6监听，有没有可能添加一个面板的关闭，重启等操作的管理脚本？

**Comment by midoks** [comment]
service mw start|stop
systemctl start mw
systemctl stop mw

**Comment by midoks** [comment]
功能已经修复。
