### ISSUE TITLE
安装完成后怎么访问管理面板呢？

### ISSUE THREAD

**Issue by TsaiQuinn** [midoks/mdserver-web#6]
执行完curl -fsSL  https://raw.githubusercontent.com/midoks/mdserver-web/master/scripts/install.sh | sh
这个命令后，怎么访问管理面板呢？

**Comment by TsaiQuinn** [comment]
谢谢回复哈。
的确是没有呀，我还纳闷文档里面怎么没有说呢，安装完了怎么进入文档里面的控制面板呢。也有可能是我操作的问题，我下次再试试

发自我的iPhone

**Comment by midoks** [comment]
> 谢谢回复哈。 的确是没有呀，我还纳闷文档里面怎么没有说呢，安装完了怎么进入文档里面的控制面板呢。也有可能是我操作的问题，我下次再试试 发自我的iPhone
> […](#)
> 在 2021年10月21日，17:56，Mr Chen ***@***.***> 写道： ﻿ 没有提示？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


![1635662927791](https://user-images.githubusercontent.com/4169529/139571778-4a2d7c91-48b6-41d2-bdb4-a793682779b3.jpg)

**Comment by TsaiQuinn** [comment]
应该是我这边环境的问题，
第一次执行安装命令：






执行完后没有像你那样的提示，然后第二次执行安装命令：




最后用了你的这个：





多谢，多谢～








CK
***@***.***
