### ISSUE TITLE
面板重启就不能访问了

### ISSUE THREAD

**Issue by neticns** [midoks/mdserver-web#60]
怎么回事

**Comment by midoks** [comment]
ubtuntu,debian自启动有问题，已经解决。更新一下，就行了。

**Comment by neticns** [comment]
重启服务器解决了.不过我是centos系统

**Comment by midoks** [comment]
由以前的chkconfig 改成systemd.启动方式全部改变。

**Comment by neticns** [comment]
> 由以前的chkconfig 改成systemd.启动方式全部改变。

好的
