### ISSUE TITLE
这俩启动不了

### ISSUE THREAD

**Issue by neticns** [midoks/mdserver-web#61]
![B5BC45BB-1376-4059-A47F-399E86AE656E](https://user-images.githubusercontent.com/106292753/174435956-02d75a4f-a870-4267-a7db-4ddc7a3c49b5.jpeg)
可真费劲

**Comment by midoks** [comment]
为了兼容其他系统，正在处理中。
等稳定后，会释出新版。
现在可以为找bug。

按道理openresty 不会出问题。

**Comment by neticns** [comment]
这两个支持什么系统？我准备换个

**Comment by midoks** [comment]
php,openresty 已经改了，不会动了。
正在改mysql。

卸载后，重装就行了。

**Comment by neticns** [comment]
mysql也是启动不了

**Comment by neticns** [comment]
> php,openresty 已经改了，不会动了。 正在改mysql。
> 
> 卸载后，重装就行了。

还是不行

**Comment by zhjue** [comment]
@midoks 请问下一个稳定版啥时候发布呀

**Comment by midoks** [comment]
我更新是因为终于有人关注了。以前我自己用。centos一个系统，基本上没有问题。


如果没有人用，我是没有动力更新的。
突然这么多人关注，我是懵逼的。这几天，才开始更新的。

1.首先兼容。基本完成。
2.重要插件兼容。【30%】
3.非重要插件，看清空更新。
4.非重要插件，要剔除。【转移到其他地方】
5.插件开发文档。我不可能开发所有的插件需求。

基本上是这样想的。

一个半月。搞定重要的。
然后要停停写写。修复bug。
然后一个半月，没有大问题。就可以发布新版了吧。

**Comment by neticns** [comment]
> 我更新是因为终于有人关注了。以前我自己用。centos一个系统，基本上没有问题。
> 
> ![image](https://user-images.githubusercontent.com/4169529/174442430-88daa8db-2394-45da-9ae8-a4da775346c0.png)
> 
> 如果没有人用，我是没有动力更新的。 突然这么多人关注，我是懵逼的。这几天，才开始更新的。
> 
> 1.首先兼容。基本完成。 2.重要插件兼容。【30%】 3.非重要插件，看清空更新。 4.非重要插件，要剔除。【转移到其他地方】 5.插件开发文档。我不可能开发所有的插件需求。
> 
> 基本上是这样想的。
> 
> 一个半月。搞定重要的。 然后要停停写写。修复bug。 然后一个半月，没有大问题。就可以发布新版了吧。 【三个月】。 不排除意外情况。会更久一点。

我从全球论坛过来的，因为宝塔自私收集客户信息

**Comment by neticns** [comment]
宝塔收集信息他们都不敢用了，所以好多人都卸载宝塔用其他面板了，你尽快发布稳定版收割更多用户

**Comment by doublog** [comment]
这里应该大部分都是loc过来的，哈哈，不过确实也因为centos太过那什么，所以现在很多都是用debian或者ubuntu了吧。我测试过debian和ubuntu，确实是有很多问题存在。

**Comment by ZiXia1** [comment]
不能只白嫖吧，至少也得贡献一下，如提交点pull

**Comment by weiyidu** [comment]
> 我更新是因为终于有人关注了。以前我自己用。centos一个系统，基本上没有问题。
> 
> ![image](https://user-images.githubusercontent.com/4169529/174442430-88daa8db-2394-45da-9ae8-a4da775346c0.png)
> 
> 如果没有人用，我是没有动力更新的。 突然这么多人关注，我是懵逼的。这几天，才开始更新的。
> 
> 1.首先兼容。基本完成。 2.重要插件兼容。【30%】 3.非重要插件，看清空更新。 4.非重要插件，要剔除。【转移到其他地方】 5.插件开发文档。我不可能开发所有的插件需求。
> 
> 基本上是这样想的。
> 
> 一个半月。搞定重要的。 然后要停停写写。修复bug。 然后一个半月，没有大问题。就可以发布新版了吧。 【三个月】。 不排除意外情况。会更久一点。

作为第一位在论坛宣传推动者，我很开心有这么多人使用。

**Comment by neticns** [comment]
> 

谢谢你啊，不然也不会遇到这么好的面板

**Comment by midoks** [comment]
防火墙在OpenResty版不兼容。
