### ISSUE TITLE
给大佬新版本提点建议

### ISSUE THREAD

**Issue by ycgz2008** [midoks/mdserver-web#62]
大佬，一些必须的功能麻烦添加一下
1、反向代理、重定向
2、Fail2ban防爆破 1.7、谷歌云网盘 2.0（将网站或数据库或指定目录数据打包备份到谷歌云网盘）、openrasp管理器 6.0
4、网站监控报表、宝塔一键迁移API版本 3.2

**Comment by midoks** [comment]
你这个需求太多，
短时间无法完成。

之前说三个月，是不加功能。

加上你这个需求，又是三个月了。

**Comment by neticns** [comment]
> 你这个需求太多， 短时间无法完成。
> 
> 之前说三个月，是不加功能。
> 
> 加上你这个需求，又是三个月了。
> 
> 要慢慢等咯。。

稳定版本先上，后续慢慢加插件

**Comment by pxw2002** [comment]
借楼问一下 这个以后有收费计划吗

**Comment by midoks** [comment]
永久免费，直到不需要的服务器！

**Comment by mengdodo** [comment]
> 

嘿嘿，我要你截图保存

**Comment by tension** [comment]
建议增加 Google PageSpeed 插件

**Comment by oldyibin** [comment]
> 你这个需求太多， 短时间无法完成。
> 
> 之前说三个月，是不加功能。
> 
> 加上你这个需求，又是三个月了。
> 
> 要慢慢等咯。。

建议收费，或者程序后台也增加赞赏二维码，靠爱发电太不容易了。

**Comment by a937983423** [comment]
我咋感觉是宝塔面板呢

**Comment by a937983423** [comment]
太像宝塔面板了
