### ISSUE TITLE
lxc 容器下 获取的运行时间为 宿主机 的运行时间

### ISSUE THREAD

**Issue by soxft** [midoks/mdserver-web#67]
lxc 容器下 获取的运行时间为 宿主机 的运行时间

**Comment by soxft** [comment]
https://github.com/midoks/mdserver-web/blob/1ef75be5d60e89308abdc9579b12a8e0ebaf5911/class/core/system_api.py#L255

感觉直接读 /proc/uptime 也是可以的呀, 为什么要改掉呢 😂

**Comment by soxft** [comment]
> ![image](https://user-images.githubusercontent.com/4169529/174579778-fd9ce2cc-6ec2-493a-baeb-7186ca936bc3.png)
> 看了一下代码，是为了兼容。

那或者可以 先从 /proc/uptime 获取, 如果 `No such file or directory` 再使用 psutil.boot_time 获取开机时间 ?

**Comment by midoks** [comment]
既然你那么深入了，为什么不提交PR呢。

**Comment by soxft** [comment]
> 既然你那么深入了，为什么不提交PR呢。一起共建和谐美好家园！

啊😂 我晚上改了试下
