### ISSUE TITLE
请问支持哪些linux系统和版本，我试图安装体验，但安装不上，请您写一个相对详细的教程。感谢！

### ISSUE THREAD

**Issue by guihuatu2022** [midoks/mdserver-web#7]
请问支持哪些linux系统和版本，我试图安装体验，但安装不上，请您写一个相对详细的教程。感谢！

**Comment by midoks** [comment]
暂时只支持centos。其他没有测试。


### 自动安装
```
curl -fsSL  https://raw.githubusercontent.com/midoks/mdserver-web/master/scripts/install.sh | sh
```

如果按照失败。请给出报错信息。

**Comment by Spark100k** [comment]
4.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
     |████████████████████████████████| 280 kB 10.0 MB/s
Installing collected packages: psutil
Successfully installed psutil-5.9.1
Collecting pymongo
  Downloading pymongo-4.1.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (462 kB)
     |████████████████████████████████| 462 kB 8.6 MB/s
Installing collected packages: pymongo
Successfully installed pymongo-4.1.1
bash: line 136: ./scripts/init.d/mw: No such file or directory
Time consumed: 10 Minute!
安装报错，最小化版centos7.9. 还原快照 重装3次了  都是安装失败。
 cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
