### ISSUE TITLE
feta: 一些 CLI 中的快捷操作

### ISSUE THREAD

**Issue by soxft** [midoks/mdserver-web#72]
比如 在 ssh 中 快捷修改用户名 密码 等操作

**Comment by soxft** [comment]
好像 wiki 里有 😂

**Comment by soxft** [comment]
可以考虑 将 cli.sh 软链接到 /usr/bin/mdserver 之类的 将一些常用操作 集成到 cli.sh 中

https://github.com/midoks/mdserver-web/wiki/密码修改

wiki 中的命令 最好指定 面板使用的python 版本 `cd /www/server/mdserver-web/ &&./bin/python tools.py  panel passwd123`

**Comment by ffsir** [comment]
可以考虑出一个一键管理脚本 类似某bt
