### ISSUE TITLE
安装之后没有输出面板信息，修改username和password也修改不了

### ISSUE THREAD

**Issue by 2lifetop** [midoks/mdserver-web#73]
`bash: line 117: ./scripts/init.d/mw: No such file or directory`
安装最后的提示。系统方面测试了Debian11,10，Ubuntu20，centos8.5, 7.9
服务器hetzner
![Termius_BJH34BmMir](https://user-images.githubusercontent.com/57310468/174651244-efbd5130-d99d-47d0-adf4-c7e39cd9842d.png)
登陆页面可以打开。
建议老哥在dev分支上开发测试，master还是以稳定为主。或者也分开发版和稳定版两种安装方式。
感谢大佬的开发。

**Comment by cjx2000** [comment]
再执行一下安装程序，就会出来了。

**Comment by soxft** [comment]
> `bash: line 117: ./scripts/init.d/mw: No such file or directory`
> 
> 安装最后的提示。系统方面测试了Debian11,10，Ubuntu20，centos8.5, 7.9
> 
> 服务器hetzner
> 
> ![Termius_BJH34BmMir](https://user-images.githubusercontent.com/57310468/174651244-efbd5130-d99d-47d0-adf4-c7e39cd9842d.png)
> 
> 登陆页面可以打开。
> 
> 建议老哥在dev分支上开发测试，master还是以稳定为主。或者也分开发版和稳定版两种安装方式。
> 
> 感谢大佬的开发。
> 
> 


修改密码的时候 要指定面板使用的python环境
可以看下 #72

**Comment by yichen666888** [comment]
大佬  忘记密码了,新执行升级或安装脚本终端显示的账号密码不对，执行修改密码的命令提示：Traceback (most recent call last):
  File "tools.py", line 16, in <module>
    import psutil
ImportError: No module named psutil

**Comment by soxft** [comment]
> 大佬 忘记密码了,新执行升级或安装脚本终端显示的账号密码不对，执行修改密码的命令提示：Traceback (most recent call last):
> File "tools.py", line 16, in 
> import psutil
> ImportError: No module named psutil

试试 /www/server/mdserver-web/bin/python -m pip install psutil

**Comment by soxft** [comment]
> 大佬 忘记密码了,新执行升级或安装脚本终端显示的账号密码不对，执行修改密码的命令提示：Traceback (most recent call last):
> File "tools.py", line 16, in 
> import psutil
> ImportError: No module named psutil

试试 /www/server/mdserver-web/bin/python -m pip install psutil

**Comment by yichen666888** [comment]
> > 大佬 忘记密码了,新执行升级或安装脚本终端显示的账号密码不对，执行修改密码的命令提示：Traceback (most recent call last):
> > File "tools.py", line 16, in
> > import psutil
> > ImportError: No module named psutil
> 
> 试试 /www/server/mdserver-web/bin/python -m pip install psutil

提示Requirement already satisfied: psutil in ./lib/python3.6/site-packages (5.9.1)  ！再次执行重置密码问题依旧复现

**Comment by soxft** [comment]
> > > 大佬 忘记密码了,新执行升级或安装脚本终端显示的账号密码不对，执行修改密码的命令提示：Traceback (most recent call last):
> > > File "tools.py", line 16, in
> > > import psutil
> > > ImportError: No module named psutil
> > 
> > 
> > 试试 /www/server/mdserver-web/bin/python -m pip install psutil
> 
> 提示Requirement already satisfied: psutil in ./lib/python3.6/site-packages (5.9.1) ！再次执行重置密码问题依旧复现，并且 mw default 不存在此命令

cd /www/server/mdserver-web/ && /www/server/mdserver-web/bin/python tools.py  panel passwd123
试试这样?

**Comment by yichen666888** [comment]
> > > > 大佬 忘记密码了,新执行升级或安装脚本终端显示的账号密码不对，执行修改密码的命令提示：Traceback (most recent call last):
> > > > File "tools.py", line 16, in
> > > > import psutil
> > > > ImportError: No module named psutil
> > > 
> > > 
> > > 试试 /www/server/mdserver-web/bin/python -m pip install psutil
> > 
> > 
> > 提示Requirement already satisfied: psutil in ./lib/python3.6/site-packages (5.9.1) ！再次执行重置密码问题依旧复现，并且 mw default 不存在此命令
> 
> cd /www/server/mdserver-web/ && /www/server/mdserver-web/bin/python tools.py panel passwd123 试试这样?

这个可以   已解决  感谢！
