### ISSUE TITLE
数据库打开是这个问题

### ISSUE THREAD

**Issue by siamoe** [midoks/mdserver-web#76]
bin/sh: 5.6: command not found /bin/sh: 8.0: command not found /bin/sh: 5.7: command not found Exception ignored in: <_io.TextIOWrapper name='' mode='w' encoding='UTF-8'> BrokenPipeError: [Errno 32] Broken pipe

**Comment by midoks** [comment]
看不到，有用的信息。

**Comment by siamoe** [comment]
InnoDB: Database physically writes the file full: wait...
220623 13:23:38  InnoDB: Log file /www/server/mysql/data/ib_logfile1 did not exist: new to be created
InnoDB: Setting log file /www/server/mysql/data/ib_logfile1 size to 5 MB
InnoDB: Database physically writes the file full: wait...
InnoDB: Doublewrite buffer not found: creating new
InnoDB: Doublewrite buffer created
InnoDB: 127 rollback segment(s) active.
InnoDB: Creating foreign key constraint system tables
InnoDB: Foreign key constraint system tables created
220623 13:23:38  InnoDB: Waiting for the background threads to start
220623 13:23:39 InnoDB: 5.5.62 started; log sequence number 0
220623 13:23:40 [Note] Server hostname (bind-address): &#x27;0.0.0.0&#x27;; port: 3306
220623 13:23:40 [Note]   - &#x27;0.0.0.0&#x27; resolves to &#x27;0.0.0.0&#x27;;
220623 13:23:40 [Note] Server socket created on IP: &#x27;0.0.0.0&#x27;.
220623 13:23:40 [Note] Event Scheduler: Loaded 0 events
220623 13:23:40 [Note] /www/server/mysql/bin/mysqld: ready for connections.
Version: &#x27;5.5.62-log&#x27;  socket: &#x27;/www/server/mysql/mysql.sock&#x27;  port: 3306  Source distribution

**Comment by midoks** [comment]
已经修复。mysql5.7,8.0需要更高的配置。不然很很容被kernel给kill。也可以开启swap插件【添加虚拟内存】。
