### ISSUE TITLE
能不能搞个docker管理器

### ISSUE THREAD

**Issue by trackcn** [midoks/mdserver-web#77]
能不能搞个docker管理器

**Comment by emengweb** [comment]
确实用到docker的地方越来越多，如果有个管理器会方便许多呢

**Comment by Envov** [comment]
虽然关闭了，但是我确实需要一个在线docker管理工具

**Comment by York618** [comment]
> 虽然关闭了，但是我确实需要一个在线docker管理工具

可以试试portainer
另外，k8s自带面板
