### ISSUE TITLE
已宣传到HostLoc，各位MJJ苦宝塔久矣

### ISSUE THREAD

**Issue by weiyidu** [midoks/mdserver-web#8]
https://hostloc.com/thread-1030420-1-1.html

**Comment by luodaoyi** [comment]
支持支持!!

**Comment by cnvoa** [comment]
观光团

**Comment by jiqing112** [comment]
前来支持一下，感谢开源。

**Comment by dreampen123** [comment]
感谢，安装看看哈，已star

**Comment by idc-care** [comment]
不错

**Comment by midoks** [comment]
你们把我吓到了，突然这么多star。

**Comment by weiyidu** [comment]
> 你们把我吓到了，突然这么多star。

这就说明不想用BT的很多，但是这样你会不会被发律师函。

**Comment by weiyidu** [comment]
> 你们把我吓到了，突然这么多star。

结合这个 https://github.com/flucont/btcloud

**Comment by weiyidu** [comment]
> > 你们把我吓到了，突然这么多star。
> 
> 这就说明不想用BT的很多，但是这样你会不会被发律师函。

它的协议 https://www.bt.cn/new/agreement_open.html

**Comment by mengyalei** [comment]
顶

**Comment by weiyidu** [comment]
52破解宣传了一波，感觉很受欢迎。

**Comment by mengdodo** [comment]
> > > > 你们把我吓到了，突然这么多star。
> > > 
> > > 
> > > 这就说明不想用BT的很多，但是这样你会不会被发律师函。
> > 
> > 
> > 它的协议 https://www.bt.cn/new/agreement_open.html
> 
> 2.1 以自用为目的，可将堡塔用于盈利或非盈利项目上，且不受任何限制。我又没有盈利，也不准备盈利，只为自己管理的小服务器用。

这波你不🔥没道理

**Comment by yangliuchang** [comment]
过来围观

**Comment by yichen666888** [comment]
前排支持！！！  不过还是建议换个UI，现在的大环境就算不盈利也那个啥。。。
