### ISSUE TITLE
没有卸载脚本吗

### ISSUE THREAD

**Issue by lvtai-py** [midoks/mdserver-web#81]
ssl申请证书有点问题，会一直转
还有就是没有卸载脚本想卸了重装来着

**Comment by midoks** [comment]
试试这个
```
curl https://get.acme.sh | sh
```

**Comment by midoks** [comment]
> > 希望可以放个收款码

就在首页呀

**Comment by xiaomoy** [comment]
> > > 希望可以放个收款码
> 
> 就在首页呀

请问如何卸载，想重新安装一下。是直接删除www吗

**Comment by midoks** [comment]
1。删除mdserver-web  
rm -rf /www/server/mdserver-web
2. 删除安装的软件
rm -rf /www/server
