### ISSUE TITLE
弄API接口呗。开虚拟空间给用户使用。

### ISSUE THREAD

**Issue by Koxue** [midoks/mdserver-web#86]
类似kangle的API系统。

**Comment by gaoyuoppa** [comment]
非基础功能,开发权重安排低,等吧,等不及也是急需的就付费定制吧.

**Comment by DaoChen6** [comment]
这个得慢慢来

**Comment by Laogesix** [comment]
你这需求还是直接用康乐吧

**Comment by midoks** [comment]
> 类似kangle的API系统。

我看了一下kangle系统，我觉得这款软件非常优秀。

![image](https://user-images.githubusercontent.com/4169529/175958336-dabc1763-8461-45a2-8066-d81ec18b210b.png)

同样的BT也很优秀。

我和他们定位是不一样的。以后会搞一些接口，但是不会搞虚拟空间多用户管理。这个概念太老了，云服务器已经大行其道。

像BT这种公司级别应该开发一下，我就算了，😊。
