### ISSUE TITLE
Redis 6.2.7启动会还原配置

### ISSUE THREAD

**Issue by SeniraPuthor** [midoks/mdserver-web#87]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/40388528/175047832-3ff24b12-2e8d-4399-b930-cf0f8d9e4ce7.png">
redis绑定到0.0.0.0不安全我修改配置，在面板上重启redis后配置文件会还原到默认的。

**Comment by midoks** [comment]
已经修复
