### ISSUE TITLE
debain 10  安装 php53 无法正常安装。

### ISSUE THREAD

**Issue by zhe1253** [midoks/mdserver-web#97]
## 什么系统 ?

debain 10  安装 php 53  无法正常安装成功。

## 错误信息 ?

2022-06-24 08:01:43 (3.63 MB/s) - ‘/www/server/source/php/php-5.3.29.tar.xz’ saved [9142540/9142540]

+ cd /www/server/source/php
+ tar -Jxf /www/server/source/php/php-5.3.29.tar.xz
+ mv /www/server/source/php/php-5.3.29 /www/server/source/php/php53
+ '[' -f /www/server/php/53/bin/php ']'
+ OPTIONS=
+ '[' Linux == Darwin ']'
+ OPTIONS=--with-iconv=/www/server/lib/libiconv
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old --with-gd --enable-gd-native-ttf'
+ OPTIONS='--with-iconv=/www/server/lib/libiconv --with-freetype-dir=/www/server/lib/freetype_old --with-gd --enable-gd-native-ttf --with-curl'
+ '[' '!' -d /www/server/php/53 ']'
+ '[' -f /www/server/php/53/bin/php.dSYM ']'
+ '[' -f /www/server/php/53/sbin/php-fpm.dSYM ']'
+ '[' '!' -d /www/server/php/53/lib/php/extensions/no-debug-non-zts-20090626 ']'

实际上多次测试，debain 10  和 debain 11  都无法正常安装 php53 和 php73 ,多次测试都无法正常安装。
...

**Comment by zhe1253** [comment]
安装php73的错误信息：
Makefile:899: warning: ignoring old recipe for target 'ext/standard/sha1.lo'
Makefile:1821: warning: overriding recipe for target 'ext/standard/user_filters.lo'
Makefile:901: warning: ignoring old recipe for target 'ext/standard/user_filters.lo'
Makefile:1823: warning: overriding recipe for target 'ext/standard/uuencode.lo'
Makefile:903: warning: ignoring old recipe for target 'ext/standard/uuencode.lo'
Makefile:1825: warning: overriding recipe for target 'ext/standard/filters.lo'
Makefile:905: warning: ignoring old recipe for target 'ext/standard/filters.lo'
Makefile:1827: warning: overriding recipe for target 'ext/standard/proc_open.lo'
Makefile:907: warning: ignoring old recipe for target 'ext/standard/proc_open.lo'
Makefile:1829: warning: overriding recipe for target 'ext/standard/streamsfuncs.lo'
Makefile:909: warning: ignoring old recipe for target 'ext/standard/streamsfuncs.lo'
Makefile:1831: warning: overriding recipe for target 'ext/standard/http.lo'
Makefile:911: warning: ignoring old recipe for target 'ext/standard/http.lo'
Makefile:1833: warning: overriding recipe for target 'ext/standard/password.lo'
Makefile:913: warning: ignoring old recipe for target 'ext/standard/password.lo'
Makefile:1835: warning: overriding recipe for target 'ext/standard/random.lo'
Makefile:915: warning: ignoring old recipe for target 'ext/standard/random.lo'
Makefile:1837: warning: overriding recipe for target 'ext/standard/net.lo'
Makefile:917: warning: ignoring old recipe for target 'ext/standard/net.lo'
Makefile:1839: warning: overriding recipe for target 'ext/standard/hrtime.lo'
Makefile:919: warning: ignoring old recipe for target 'ext/standard/hrtime.lo'
/bin/sh /www/server/source/php/php73/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php73/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php73/include -I/www/server/source/php/php73/main -I/www/server/source/php/php73 -I/www/server/source/php/php73/ext/date/lib -I/usr/include/libxml2 -I/www/server/lib/zlib/include -I/usr/include/x86_64-linux-gnu -I/www/server/lib/freetype_old/include/freetype2 -I/www/server/lib/libiconv/include -I/www/server/source/php/php73/ext/mbstring/oniguruma -I/www/server/source/php/php73/ext/mbstring/libmbfl -I/www/server/source/php/php73/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php73/ext/sqlite3/libsqlite -I/www/server/source/php/php73/TSRM -I/www/server/source/php/php73/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -DZEND_SIGNALS    -c /www/server/source/php/php73/ext/opcache/ZendAccelerator.c -o ext/opcache/ZendAccelerator.lo
In file included from /www/server/source/php/php73/Zend/../TSRM/TSRM.h:23,
from /www/server/source/php/php73/Zend/zend_portability.h:47,
from /www/server/source/php/php73/Zend/zend_types.h:25,
from /www/server/source/php/php73/Zend/zend.h:27,
from /www/server/source/php/php73/main/php.h:33,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/main/php_stdint.h:111:4: error: #error "No suitable 16bit integer type found"
#  error "No suitable 16bit integer type found"
^~~~~
/www/server/source/php/php73/main/php_stdint.h:127:4: error: #error "No suitable 16bit integer type found"
#  error "No suitable 16bit integer type found"
^~~~~
In file included from /www/server/source/php/php73/Zend/zend_range_check.h:22,
from /www/server/source/php/php73/Zend/zend_portability.h:77,
from /www/server/source/php/php73/Zend/zend_types.h:25,
from /www/server/source/php/php73/Zend/zend.h:27,
from /www/server/source/php/php73/main/php.h:33,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/Zend/zend_long.h:126:3: error: #error "Unknown SIZEOF_SIZE_T"
# error "Unknown SIZEOF_SIZE_T"
^~~~~
In file included from /www/server/source/php/php73/Zend/zend.h:27,
from /www/server/source/php/php73/main/php.h:33,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/Zend/zend_types.h:296:3: error: #error "Unknown SIZEOF_SIZE_T"
# error "Unknown SIZEOF_SIZE_T"
^~~~~
In file included from /www/server/source/php/php73/Zend/zend.h:27,
from /www/server/source/php/php73/main/php.h:33,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/Zend/zend_types.h:1048:3: error: #error "Unknown SIZEOF_SIZE_T"
# error "Unknown SIZEOF_SIZE_T"
^~~~~
In file included from /www/server/source/php/php73/Zend/zend.h:27,
from /www/server/source/php/php73/main/php.h:33,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/Zend/zend_hash.h: In function ‘_zend_hash_append_ex’:
/www/server/source/php/php73/Zend/zend_types.h:1057:3: warning: implicit declaration of function ‘ZVAL_COPY_VALUE_EX’; did you mean ‘ZVAL_COPY_VALUE’? [-Wimplicit-function-declaration]
ZVAL_COPY_VALUE_EX(_z1, _z2, _gc, _t);   \
^~~~~~~~~~~~~~~~~~
/www/server/source/php/php73/Zend/zend_hash.h:1080:2: note: in expansion of macro ‘ZVAL_COPY_VALUE’
ZVAL_COPY_VALUE(&p->val, zv);
^~~~~~~~~~~~~~~
In file included from /www/server/source/php/php73/Zend/zend.h:32,
from /www/server/source/php/php73/main/php.h:33,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/Zend/zend_hash.h:1090:24: warning: implicit declaration of function ‘HT_IDX_TO_HASH’; did you mean ‘HT_SIZE_TO_MASK’? [-Wimplicit-function-declaration]
HT_HASH(ht, nIndex) = HT_IDX_TO_HASH(idx);
^~~~~~~~~~~~~~
HT_SIZE_TO_MASK
In file included from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/main/php.h: At top level:
/www/server/source/php/php73/main/php.h:136: warning: "assert" redefined
#define assert(expr) ((void) (0))

In file included from /www/server/source/php/php73/Zend/zend_operators.h:26,
from /www/server/source/php/php73/Zend/zend.h:335,
from /www/server/source/php/php73/main/php.h:33,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/usr/include/assert.h:107: note: this is the location of the previous definition
#  define assert(expr)       \

In file included from /www/server/source/php/php73/main/php.h:466,
from /www/server/source/php/php73/ext/opcache/ZendAccelerator.c:22:
/www/server/source/php/php73/Zend/zend_virtual_cwd.h:158:9: error: unknown type name ‘DIR’
CWD_API DIR *virtual_opendir(const char *pathname);
^~~
/www/server/source/php/php73/ext/opcache/ZendAccelerator.c: In function ‘store_script_in_file_cache’:
/www/server/source/php/php73/ext/opcache/ZendAccelerator.c:1412:55: error: expected ‘)’ before ‘ZEND_ADDR_FMT’
"Internal error: wrong size calculation: %s start=" ZEND_ADDR_FMT ", end=" ZEND_ADDR_FMT ", real=" ZEND_ADDR_FMT "\n",
^~~~~~~~~~~~~~
)
/www/server/source/php/php73/ext/opcache/ZendAccelerator.c: In function ‘cache_script_in_shared_memory’:
/www/server/source/php/php73/ext/opcache/ZendAccelerator.c:1577:55: error: expected ‘)’ before ‘ZEND_ADDR_FMT’
"Internal error: wrong size calculation: %s start=" ZEND_ADDR_FMT ", end=" ZEND_ADDR_FMT ", real=" ZEND_ADDR_FMT "\n",
^~~~~~~~~~~~~~
)
make: *** [Makefile:1519: ext/opcache/ZendAccelerator.lo] Error 1

**Comment by zhe1253** [comment]
php 74 安装错误提示：

checking for usable _controlfp_s... no
checking whether FPU control word can be manipulated by inline assembler... yes
checking whether double cast to long preserves least significant bits... no
checking for dlfcn.h... (cached) yes
checking whether dlsym() requires a leading underscore in symbol names... no
checking whether to enable thread-safety... no
checking whether to enable inline optimization for GCC... yes
checking whether to enable Zend debugging... no
checking for inline... inline
checking target system is Darwin... no
checking for MM alignment and log values... done
checking for mremap... yes
checking for sigaction... yes
checking whether to enable zend signal handling... yes

[1mConfiguring TSRM[m

[1mConfiguring libtool[m
checking for a sed that does not truncate output... /bin/sed
checking for ld used by cc... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for /bin/ld option to reload object files... -r
checking for BSD-compatible nm... /bin/nm -B
checking how to recognize dependent libraries... pass_all
checking the maximum length of command line arguments... 1572864
checking command to parse /bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes

creating libtool
appending configuration tag "CXX" to libtool

[1mGenerating files[m
configure: patching main/php_config.h.in
configure: creating ./config.status
creating main/internal_functions.c
creating main/internal_functions_cli.c
config.status: creating main/build-defs.h
config.status: creating scripts/phpize
config.status: creating scripts/man1/phpize.1
config.status: creating scripts/php-config
config.status: creating scripts/man1/php-config.1
config.status: creating sapi/cli/php.1
config.status: creating sapi/fpm/php-fpm.conf
config.status: creating sapi/fpm/www.conf
config.status: creating sapi/fpm/init.d.php-fpm
config.status: creating sapi/fpm/php-fpm.service
config.status: creating sapi/fpm/php-fpm.8
config.status: creating sapi/fpm/status.html
config.status: creating sapi/phpdbg/phpdbg.1
config.status: creating sapi/cgi/php-cgi.1
config.status: creating ext/phar/phar.1
config.status: creating ext/phar/phar.phar.1
config.status: creating main/php_config.h
config.status: main/php_config.h is unchanged
config.status: executing default commands

+--------------------------------------------------------------------+
| License:                                                           |
| This software is subject to the PHP License, available in this     |
| distribution in the file LICENSE. By continuing this installation  |
| process, you are bound by the terms of this license agreement.     |
| If you do not agree with the terms of this license, you must abort |
| the installation process at this point.                            |
+--------------------------------------------------------------------+

Thank you for using PHP.

configure: WARNING: unrecognized options: --with-freetype-dir, --with-gd, --enable-gd-native-ttf, --with-libzip
+ make
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/sccp.c -o ext/opcache/Optimizer/sccp.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/scdf.c -o ext/opcache/Optimizer/scdf.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/dce.c -o ext/opcache/Optimizer/dce.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/escape_analysis.c -o ext/opcache/Optimizer/escape_analysis.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/escape_analysis.c -o ext/opcache/Optimizer/escape_analysis.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/compact_vars.c -o ext/opcache/Optimizer/compact_vars.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/compact_vars.c -o ext/opcache/Optimizer/compact_vars.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/zend_dump.c -o ext/opcache/Optimizer/zend_dump.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/opcache/ -I/www/server/source/php/php74/ext/opcache/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS    -c /www/server/source/php/php74/ext/opcache/Optimizer/zend_dump.c -o ext/opcache/Optimizer/zend_dump.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=link cc -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS     -o ext/opcache/opcache.la -export-dynamic -avoid-version -prefer-pic -module -rpath /www/server/source/php/php74/modules -L/www/server/lib/libiconv/lib ext/opcache/ZendAccelerator.lo ext/opcache/zend_accelerator_blacklist.lo ext/opcache/zend_accelerator_debug.lo ext/opcache/zend_accelerator_hash.lo ext/opcache/zend_accelerator_module.lo ext/opcache/zend_persist.lo ext/opcache/zend_persist_calc.lo ext/opcache/zend_file_cache.lo ext/opcache/zend_shared_alloc.lo ext/opcache/zend_accelerator_util_funcs.lo ext/opcache/shared_alloc_shm.lo ext/opcache/shared_alloc_mmap.lo ext/opcache/shared_alloc_posix.lo ext/opcache/Optimizer/zend_optimizer.lo ext/opcache/Optimizer/pass1_5.lo ext/opcache/Optimizer/pass2.lo ext/opcache/Optimizer/pass3.lo ext/opcache/Optimizer/optimize_func_calls.lo ext/opcache/Optimizer/block_pass.lo ext/opcache/Optimizer/optimize_temp_vars_5.lo ext/opcache/Optimizer/nop_removal.lo ext/opcache/Optimizer/compact_literals.lo ext/opcache/Optimizer/zend_cfg.lo ext/opcache/Optimizer/zend_dfg.lo ext/opcache/Optimizer/dfa_pass.lo ext/opcache/Optimizer/zend_ssa.lo ext/opcache/Optimizer/zend_inference.lo ext/opcache/Optimizer/zend_func_info.lo ext/opcache/Optimizer/zend_call_graph.lo ext/opcache/Optimizer/sccp.lo ext/opcache/Optimizer/scdf.lo ext/opcache/Optimizer/dce.lo ext/opcache/Optimizer/escape_analysis.lo ext/opcache/Optimizer/compact_vars.lo ext/opcache/Optimizer/zend_dump.lo -lrt
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=link cc -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/lib/libiconv/include -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -I/www/server/lib/libiconv/include -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS     -o ext/opcache/opcache.la -export-dynamic -avoid-version -prefer-pic -module -rpath /www/server/source/php/php74/modules -L/www/server/lib/libiconv/lib ext/opcache/ZendAccelerator.lo ext/opcache/zend_accelerator_blacklist.lo ext/opcache/zend_accelerator_debug.lo ext/opcache/zend_accelerator_hash.lo ext/opcache/zend_accelerator_module.lo ext/opcache/zend_persist.lo ext/opcache/zend_persist_calc.lo ext/opcache/zend_file_cache.lo ext/opcache/zend_shared_alloc.lo ext/opcache/zend_accelerator_util_funcs.lo ext/opcache/shared_alloc_shm.lo ext/opcache/shared_alloc_mmap.lo ext/opcache/shared_alloc_posix.lo ext/opcache/Optimizer/zend_optimizer.lo ext/opcache/Optimizer/pass1_5.lo ext/opcache/Optimizer/pass2.lo ext/opcache/Optimizer/pass3.lo ext/opcache/Optimizer/optimize_func_calls.lo ext/opcache/Optimizer/block_pass.lo ext/opcache/Optimizer/optimize_temp_vars_5.lo ext/opcache/Optimizer/nop_removal.lo ext/opcache/Optimizer/compact_literals.lo ext/opcache/Optimizer/zend_cfg.lo ext/opcache/Optimizer/zend_dfg.lo ext/opcache/Optimizer/dfa_pass.lo ext/opcache/Optimizer/zend_ssa.lo ext/opcache/Optimizer/zend_inference.lo ext/opcache/Optimizer/zend_func_info.lo ext/opcache/Optimizer/zend_call_graph.lo ext/opcache/Optimizer/sccp.lo ext/opcache/Optimizer/scdf.lo ext/opcache/Optimizer/dce.lo ext/opcache/Optimizer/escape_analysis.lo ext/opcache/Optimizer/compact_vars.lo ext/opcache/Optimizer/zend_dump.lo -lrt
libtool: link: `ext/opcache/Optimizer/sccp.lo' is not a valid libtool object
make: *** [Makefile:1164: ext/opcache/opcache.la] Error 1
libtool: link: `ext/opcache/Optimizer/sccp.lo' is not a valid libtool object
make: *** [Makefile:1164: ext/opcache/opcache.la] Error 1

**Comment by zhe1253** [comment]
以上错误信息，都是 debain 10 的安装错误，
PHP53 ，PHP73, php74  三个安装错误。
基本上多次安装也是无法安装。错误信息都是一样的。

**Comment by midoks** [comment]
![image](https://user-images.githubusercontent.com/4169529/175569213-4000d8ba-57da-4a8b-a4e5-8dd198ba06ad.png)

![image](https://user-images.githubusercontent.com/4169529/175569173-a9c7a0cd-08c2-4c79-b30b-7543cfeb1944.png)

我该怎么办？

之后，我优化了脚本。你再试试。还不不行，给我你的信息，邮件发过来，在线调试一下。

**Comment by zhe1253** [comment]
感谢您为这个项目做的努力。
我收到你的回复后，重装了debain 10 ,
运行了
apt update&nbsp;&nbsp;
apt upgrade
然后安装md-server, 安装的是 dev 版本
curl -fsSL&nbsp; https://raw.githubusercontent.com/midoks/mdserver-web/dev/scripts/install_dev.sh | bash
然后使用了脚本更新
curl -fsSL&nbsp; https://raw.githubusercontent.com/midoks/mdserver-web/dev/scripts/update_dev.sh | bash


然后登陆面板，面板版本显示0.8.6.1
开始安装：
OpenResty 1.21.4.1
任务列表显示正常，安装 也是正常，
安装完成以后，设置启动和自启动，都正常。消息列表：安装[openresty-1.21.4.1]【已完成】耗时104秒




然后开始安装&nbsp; php 5.3
任务列表显示正常，安装 也是正常，
安装[php-53]【已完成】耗时312秒




然后开始安装&nbsp; php 7.3
任务列表显示正常，安装 也是正常，
安装[php-73]【已完成】耗时563秒


然后开始安装 mysql 5.5
任务列表显示正常，安装 也是正常，
安装[mysql-5.5]【已完成】耗时286秒




这次安装没有什么问题，都是一次性过的，
明天我如果有时间，会再换台VPS重装debain 10&nbsp; 或者 debain 11 来测试一
openresty+php +mysql 都安装一下试试。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr ***@***.***&gt;; 
发送时间: 2022年6月24日(星期五) 晚上11:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [midoks/mdserver-web] debain 10  安装 php53 无法正常安装。 (Issue #97)





 
Closed #97 as completed.
