### ISSUE TITLE
建议先修复基本安装成功率，现在基本网站环境还不一定一次就能正常安成功。

### ISSUE THREAD

**Issue by zhe1253** [midoks/mdserver-web#98]
这次多安装 多次系统来测试mdserver 的网站环境安装，
centos 7  基本上可以正常安装  openresty +php 53 +php 73 +mysql5.5 +防火墙  
debain 10 和 debain  基本上可以正常安装 openresty + mysql 55 + 防火墙
但是 debain 10 和 debain11 很难一次安装 php53 和 php 73, php 74 各种错误，多次重复安装也很难成功。

之前有时连openresty 都无法正常安装 ，现在修复基本上一次就能成功安装，所以希望作者尽快修复
debain 10  和 debain 11 的php 安装问题。
谢谢。

先修复能基本  centos 7  debain 10 debain 11 这样的最常用系统的最基本上的网站环境安装。感觉比增加插件什么的更急迫。

**Comment by midoks** [comment]
一直在为稳定版优化。mysql的问题即将解决。

php？我真没有遇到过。 我现在马上换系统测试一下。

**Comment by jihaomail** [comment]
一直在用debian11 ，php7.4确实安装不上

**Comment by tudou88** [comment]
centos 7.2 安装 经常失败，不知道为什么，安装成功进入面板，还需要手动安装mysql 之类，安装好插件之后 上传网站目录之类，结果打开域名404  醉了

**Comment by midoks** [comment]
> 一直在用debian11 ，php7.4确实安装不上

经测试，的确有问提，已修复。

**Comment by midoks** [comment]
> centos 7.2 安装 经常失败，不知道为什么，安装成功进入面板，还需要手动安装mysql 之类，安装好插件之后 上传网站目录之类，结果打开域名404 醉了

没有相同镜像，我这只有centos7.9。如果可以，发邮件给服务器信息，我上服务器观测一下。

**Comment by tudou88** [comment]
> > centos 7.2 安装 经常失败，不知道为什么，安装成功进入面板，还需要手动安装mysql 之类，安装好插件之后 上传网站目录之类，结果打开域名404 醉了
> 
> 没有相同镜像，我这只有centos7.9。如果可以，发邮件给服务器信息，我上服务器观测一下。

那我用7.9尝试下 没事的 我只是在测试

**Comment by jihaomail** [comment]
> > 一直在用debian11 ，php7.4确实安装不上
> 
> 经测试，的确有问提，已修复。

Debian11 安装mysql5.6后运行不起来提示错误。
/bin/sh: line 1: 5.7: command not found /bin/sh: line 1: 5.6: command not found /bin/sh: line 1: 8.0: command no

**Comment by midoks** [comment]
> > > 一直在用debian11 ，php7.4确实安装不上
> > 
> > 
> > 经测试，的确有问提，已修复。
> 
> Debian11 安装mysql5.6后运行不起来提示错误。 /bin/sh: line 1: 5.7: command not found /bin/sh: line 1: 5.6: command not found /bin/sh: line 1: 8.0: command no

发邮件给我服务器信息。我看别人也说有这种错误。我从来没有看到过了错误。5.7，5.6，8.0报错，但是，只有安装了5.6。这种错误，闻所未闻，实为罕见。

**Comment by jihaomail** [comment]
> 

你新开一个debian11，安装完mysql5.6，启动时候就会有这个提示，其他版本mysql并没有安装

**Comment by midoks** [comment]
> > 
> 
> 你新开一个debian11，安装完mysql5.6，启动时候就会有这个提示，其他版本mysql并没有安装

![image](https://user-images.githubusercontent.com/4169529/175810350-be11317c-2ce0-4086-85df-294eec4d0dda.png)

**Comment by dreampen123** [comment]
的确，确保基本保证常见系统安装成功率，最基本的，php，sql  openresty phpadmin 各个版本都成功，再这个基础上再开发新功能，测试挺多，sql 8 基本没成功过，说后台安装了可能，但是phpadmin根本打不开，基础功能不行，留不住人的，等稳定版。

**Comment by midoks** [comment]
> 的确，确保基本保证常见系统安装成功率，最基本的，php，sql openresty phpadmin 各个版本都成功，再这个基础上再开发新功能，测试挺多，sql 8 基本没成功过，说后台安装了可能，但是phpadmin根本打不开，基础功能不行，留不住人的，等稳定版。

phpmyadmin打不开是waf的问题。已经修复。 
mysql8.0从上次合并代码，我就没有失败过。😭

**Comment by zhe1253** [comment]
昨天测试中，发现 如果VPS 无法访问  cdn.mysql.com的时候，程序脚本会无限制的重试链接，
看看是不是需要设定一个计数器，实在连接不上的时候，达到尝试N次后，直接失败，中止安装脚本。

**Comment by dreampen123** [comment]
> 
wget --no-check-certificate -O AutoReinstall.sh https://cdn.jsdelivr.net/gh/fcurrk/reinstall@master/AutoReinstall.sh && chmod a+x AutoReinstall.sh && bash AutoReinstall.sh

用这个脚本dd重装centos，depian  sql8 都不成功，希望大神有时间测试下。

**Comment by midoks** [comment]
基本over。快去测试吧
